### ISSUE TITLE
Validate throws unexpected "Context reference name mismatch" warning for urn:nasa:pds:context:instrument_host:spacecraft.pvmp.lp

### ISSUE THREAD

**Issue by smclaughlin7** [NASA-PDS-Incubator/validate#1013]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

Validate 3.5.2 throws this warning on the basic product label "v2_ks-18m.xml" in
[v2_ks-18m.zip](https://github.com/user-attachments/files/17168814/v2_ks-18m.zip):

> WARNING  [warning.label.context_ref_mismatch]   line 44: Context reference name mismatch. Value: 'PIONEER VENUS LARGE PROBE' Expected one of: '[PIONEER VENUS MULTIPROBE]'

The instrument host <name> specified in the label matches the <title> in [context product urn:nasa:pds:context:instrument_host:spacecraft.pvmp.lp](https://pds.nasa.gov/data/pds4/context-pds4/instrument_host/spacecraft.pvmp.lp_1.0.xml): "PIONEER VENUS LARGE PROBE".
 
However, the registered_context_products.json file, which is distributed with Validate 3.5.2, specifies the wrong name:
 
               "name": ["PIONEER VENUS MULTIPROBE"],
               "type": ["Spacecraft"],"
               "lidvid": "urn:nasa:pds:context:instrument_host:spacecraft.pvmp.lp::1.0"

I ran "validate -u" as Jordan recommended but it did not correct that name in my local JSON file.  (It did make a few other updates in that file.)  Jordan mentioned those values come directly from the database.

Could the registered_context_products.json file be corrected in the next Validate release?
 

### 🕵️ Expected behavior

Since the instrument host <name> specified in the label matches the <title> in [context product urn:nasa:pds:context:instrument_host:spacecraft.pvmp.lp](https://pds.nasa.gov/data/pds4/context-pds4/instrument_host/spacecraft.pvmp.lp_1.0.xml), I expected to get no warning message.
 

### 📜 To Reproduce

1. Run validate 3.5.2 (confirm it is using the registered_context_products.json file that is distributed with that version) on the attached label:  `> validate v2_ks-18m.xml`

### 🖥 Environment Info

- Version of this PDS software:  Validate 3.5.2
- Operating System: macOS Sonoma 14.7
- Java version "21.0.4" 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 21.0.4+8-LTS-274)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.4+8-LTS-274, mixed mode, sharing)

### 📚 Version of Software Used

Validate 3.5.2

### 🩺 Test Data / Additional context

The attached zip file "v2_ks-18m.zip" includes the product data file "v2_ks-18m.dat".
 

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@smclaughlin7 we currently only match the `Instrument_Host.Name` value in order to encourage the highest level of consistency across the archive. The title can be considered a "display title", which is not necessarily appropriate for archive metadata. You are welcome to disable the check if you do not want to make the appropriate updates for this.

**Comment by smclaughlin7** [comment]
@jordanpadams My concern is that the current registered_context_products.json file specifies an incorrect and misleading name/display title for the Pioneer Venus Large Probe spacecraft/instrument_host (urn:nasa:pds:context:instrument_host:spacecraft.pvmp.lp::1.0).  The Large Probe was one of five spacecraft/instrument_hosts that comprised the "Multiprobe" component of the Pioneer Venus mission/investigation.

In the context JSON file, the name for the Large Probe entry should be changed
from:
"PIONEER VENUS MULTIPROBE"
to
"PIONEER VENUS LARGE PROBE"

Looping in @Martian-Dustdevil (Lynn -- Great handle!) because he did all the heavy lifting for us on the instrument_host context products for the Pioneer Venus Large/Day/Night/North/Bus spacecraft.

**Comment by jordanpadams** [comment]
@smclaughlin7 sorry for the misunderstanding. This needs to be updated in the context products themselves. Not validate. We are in the process of doing a scrub of these so I will add this to my list.

**Comment by Martian-Dustdevil** [comment]
So to be clear -- the <title> of the instrument_host product is currently "PIONEER VENUS LARGE PROBE"; the <name> listed under <Instrument_Host> in the same product is "PIONEER VENUS MULTIPROBE" ... Specifically what needs to happen in the context product is that the <name> for the Large Probe needs to be changed to "PIONEER VENUS LARGE PROBE"

**Comment by smclaughlin7** [comment]
@jordanpadams Sorry, my description of this 'bug' was not very clear!
@Martian-Dustdevil Thanks for clarifying <Instrument_Host> needs to be changed from "PIONEER VENUS MULTIPROBE" to "PIONEER VENUS LARGE PROBE" in the context product `urn:nasa:pds:context:instrument_host:spacecraft.pvmp.lp`.
