### ISSUE TITLE
Update PDF validation to check against flavour specified in PDF metadata

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#412]
1. Check that the flavour is 1a or 1b
2. Validate the PDF is actually valid against that version

Per Jesse S:

PDFUtil.java already uses parser.getFlavour(), but passes it into createValidator: https://github.com/NASA-PDS/validate/blob/0e9984ea92e59d34dd6d74b298ac247ddf1f382b/src/main/java/gov/nasa/pds/tools/util/PDFUtil.java#L75

Meanwhile, PDFAFlavour is just a java enum, so it should be very easy to check against: https://github.com/veraPDF/veraPDF-library/blob/6a376fbd4faf4818c6123a5bdc4ce9ea03f1db32/core/src/main/java/org/verapdf/pdfa/flavours/PDFAFlavour.java

## Related Requirements
🦄 https://github.com/NASA-PDS/validate/issues/164

**Comment by qchaupds** [comment]
The default seems to be '2b', make sure it is '1a'.  We can make sure it is '1a' with in src/main/java/gov/nasa/pds/tools/util/PDFUtil.java

```
 try (PDFAParser parser = Foundries.defaultInstance().createParser(new FileInputStream(pdfRef), PDFAFlavour.PDFA_1_A)) {

Print out the value, matches our expectation.

validateFileStandardConformity: parser.getFlavour() [1a]


```

**Comment by jordanpadams** [comment]
@tloubrieu-jpl this one is up next

**Comment by tloubrieu-jpl** [comment]
@qchaupds, @jordanpadams  I think you can create a parser without the flavour, see method https://javadoc.io/doc/org.verapdf/core/1.12.1/org/verapdf/pdfa/VeraPDFFoundry.html

PDFAParser createParser(File pdfFile)
                 throws ModelParsingException,
                        EncryptedPdfException

**Comment by qchaupds** [comment]
@tloubrieu-jpl @jordanpadams The current code does create a parser without the flavor.  When you call getFlavour(), the value of '2b' is printed (that seems to be the default)

```
    try (PDFAParser parser = Foundries.defaultInstance().createParser(new FileInputStream(pdfRef))) {
        PDFAValidator validator = Foundries.defaultInstance().createValidator(parser.getFlavour(), false);
        LOG.debug("validateFileStandardConformity: parser.getFlavour() [{}]",parser.getFlavour());
```

We can also create a parser with a particular flavor using the enum:

```
try (PDFAParser parser = Foundries.defaultInstance().createParser(new FileInputStream(pdfRef), PDFAFlavour.PDFA_1_A))
```

The challenge now as Jordan had hinted was to get the flavor from the PDF.  I am not sure that is possible.
Am I missing the point you are trying to make?  Are you hinting that we should try to validate a PDF without specifying a flavour?

**Comment by tloubrieu-jpl** [comment]
@qchaupds @jordanpadams 
I was thinking you can:
1. create the parser without the flavour
2. get the flavour, with `PDFAValidator validator = Foundries.defaultInstance().createValidator(parser.getFlavour(), false); ` as shown in the ticket above
3. use the validator with the flavour

Does that make sense ? Sorry I am trying to pull the discussion on github but that might overlap with the discussion you already had in the email thread...

**Comment by tloubrieu-jpl** [comment]
The solution as Jordan had pointed out was to validate against ‘1a’ and then ‘1b’.

It has not been found how to get the current flavour from the document.

**Comment by jpl-jengelke** [comment]
[testdata.zip](https://github.com/NASA-PDS/validate/files/8674019/testdata.zip)
