### ISSUE TITLE
validate 2.2.0-SNAPSHOT warns about a pretty benign bundle + readme.txt

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS-Incubator/validate#419]
I don't understand the warning. Previous versions of validate did not throw this warning. Sample file attached

  % validate -t bug/bundle_astromat_chem.xml
  PDS Validate Tool Report
  Configuration:
     Version                       2.2.0-SNAPSHOT
     Date                          2021-10-17T08:19:19Z
  Parameters:
     Targets                       [file:/Users/rchen/Desktop/bug/bundle_astromat_chem.xml]
     Severity Level                WARNING
     Recurse Directories           true
     File Filters Used             [*.xml, *.XML]
     Data Content Validation       on
     Product Level Validation      on
     Max Errors                    100000
     Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
  Product Level Validation Results
    PASS: file:/Users/rchen/Desktop/bug/bundle_astromat_chem.xml
        WARNING  [warning.file.not_text_mimetype]   file:/Users/rchen/Desktop/bug/readme.txt with document standard id 'null' is not correct
          1 product validation(s) completed
  Summary:
    0 error(s)
    1 warning(s)
    Product Validation Summary:
      1          product(s) passed
      0          product(s) failed
      0          product(s) skipped
    Referential Integrity Check Summary:
      0          check(s) passed
      0          check(s) failed
      0          check(s) skipped
    Message Types:
      1            warning.file.not_text_mimetype
  End of Report
  Completed execution in 3576 ms
  % 
  % 
  % ../PDS4.11.1.tools/validate-2.0.7/bin/validate -t bug/bundle_astromat_chem.xml 
  PDS Validate Tool Report
  Configuration:
     Version                       2.0.7
     Date                          2021-10-17T08:22:04Z
  Parameters:
     Targets                       [file:/Users/rchen/Desktop/bug/bundle_astromat_chem.xml]
     Severity Level                WARNING
     Recurse Directories           true
     File Filters Used             [*.xml, *.XML]
     Data Content Validation       on
     Product Level Validation      on
     Max Errors                    100000
     Registered Contexts File      /Users/rchen/PDS4.11.1.tools/validate-2.0.7/resources/registered_context_products.json
  Product Level Validation Results
    PASS: file:/Users/rchen/Desktop/bug/bundle_astromat_chem.xml
          1 product validation(s) completed
  Summary:
    0 error(s)
    0 warning(s)
    Product Validation Summary:
      1          product(s) passed
      0          product(s) failed
      0          product(s) skipped
    Referential Integrity Check Summary:
      0          check(s) passed
      0          check(s) failed
      0          check(s) skipped
  End of Report
  Completed execution in 3911 ms
  %
[bug.zip](https://github.com/NASA-PDS/validate/files/7359455/bug.zip)

**Comment by jpl-jengelke** [comment]
This passes tests with validate 2.2.0-SNAPSHOT with the error resolved.
