### ISSUE TITLE
Improve warning message for missing_context_reference

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS-Incubator/validate#421]
## 💪 Motivation
The current warning message is verbose and imprecise

## 📖 Additional Details
For 'validate -R pds4.bundle' where bundle.xml lacks a lid_reference that something below it has, the message is:
> WARNING  [warning.integrity.missing_context_reference]   The context reference 'urn:nasa:pds:context:investigation:mission.lunar_reconnaissance_orbiter' could not be found in this bundle but it was defined in urn:nasa:pds:moon_lro_lroc_boulderdata_watkins_2018:document:watkins_2018_boulderdata_archive_description::1.0. (Disable with --skip-context-reference-check flag)

I suggest:
> WARNING  [warning.integrity.missing_context_reference]  This file should reference 'urn:nasa:pds:context:investigation:mission.lunar_reconnaissance_orbiter' because its child product with LIDVID 'urn:nasa:pds:moon_lro_lroc_boulderdata_watkins_2018:document:watkins_2018_boulderdata_archive_description::1.0' references it.

Or even more concise and perhaps clearer, replace the bundle's LID with "...", i.e.
> WARNING  [warning.integrity.missing_context_reference]  This file should reference 'urn:nasa:pds:context:investigation:mission.lunar_reconnaissance_orbiter' because its child product with LIDVID '...:document:watkins_2018_boulderdata_archive_description::1.0' references it.

Note that I would not use the word "define". To me, the file with the context product defines the LID.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## ⚙️ Engineering Details

refs #69

**Comment by jordanpadams** [comment]
thanks @rchenatjpl we will update this

**Comment by jordanpadams** [comment]
I think we should go with your recommendation for option 3:

> WARNING [warning.integrity.missing_context_reference] This file should reference 'urn:nasa:pds:context:investigation:mission.lunar_reconnaissance_orbiter' because its child product with LIDVID '...:document:watkins_2018_boulderdata_archive_description::1.0' references it.

**Comment by rchenatjpl** [comment]
@jordanpadams @jpl-jengelke Did this checking totally go away? I should have saved the original test case here. Here's something I reconstructed that should trigger such a message, but validate says nothing, which is a reasonable thing to do.
[validate421.zip](https://github.com/NASA-PDS/validate/files/8383215/validate421.zip)
