### ISSUE TITLE
Validate does not allow a single-character subdirectory

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS-Incubator/validate#423]
## 🐛 Describe the bug
Validate tool fails a product if the transfer manifest .tab file has a directory spec with a single-character subdirectory. Very similar to https://github.com/NASA-PDS/validate/issues/299.

## 📜 To Reproduce
1. Run validate on the files inside [gbo.ast.alcdef-database_v1.0_20211021.zip](https://github.com/NASA-PDS/validate/files/7393508/gbo.ast.alcdef-database_v1.0_20211021.zip)
2. Read output. Or skip step 1 and read this saved output: [gbo.ast.alcdef-database_v1.0_20211021-validate.txt](https://github.com/NASA-PDS/validate/files/7393513/gbo.ast.alcdef-database_v1.0_20211021-validate.txt)

## 🕵️ Expected behavior
A directory spec such as '/data/1/' should not cause an error.

## 📚 Version of Software Used
2.1.0 (but also exists in 2.0.7. Have not tested earlier versions)

## 🩺 Test Data / Additional context
Actual data available under "To Reproduce". Going by comments from https://github.com/NASA-PDS/validate/issues/299 and the pattern shown in the validate report, perhaps adding a star after the first grouping would solve this issue?
Currently: `/?([A-Za-z0-9][A-Za-z0-9_-]*[A-Za-z0-9]/?)*`
Proposed: `/?([A-Za-z0-9]*[A-Za-z0-9_-]*[A-Za-z0-9]/?)*`

---

**Comment by jordanpadams** [comment]
From SR, looks like it will be a little more complicated:

> The directory name must not begin or end with a dash or underscore.

**Comment by jpl-jengelke** [comment]
This passes tests with validate 2.2.0-SNAPSHOT with the error resolved.
