### ISSUE TITLE
Validate does not allow SIP tab file to have lines of differing lengths

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS-Incubator/validate#424]
## 🐛 Describe the bug
Validate tool fails a product if its SIP .tab file has lines which are not all the same length.

## 📜 To Reproduce
1. Run validate on the files inside [asurpif_photos_amboycrater_v1.0_20211021.zip](https://github.com/NASA-PDS/validate/files/7393587/asurpif_photos_amboycrater_v1.0_20211021.zip)
2. Read output. Or skip step 1 and read this saved output: [asurpif_photos_amboycrater_v1.0_20211021-validate.txt](https://github.com/NASA-PDS/validate/files/7393588/asurpif_photos_amboycrater_v1.0_20211021-validate.txt)

## 🕵️ Expected behavior
This product should pass without errors.

## 📚 Version of Software Used
2.1.0

## 🩺 Test Data / Additional context

```
  FAIL: file:/asurpif_photos_amboycrater_v1.0_20211021_sip_v1.0.xml
    Begin Content Validation: file:/asurpif_photos_amboycrater_v1.0_20211021_sip_v1.0.tab
      ERROR  [error.table.record_length_mismatch]   table 1: File that ends with .tab should have same record length.  Line number:1, record length:260, Line number:3, record length:275. Exhaustive list of all line number and line length: 1:260, 3:275, 535:201, 536:277, 537:278, 539:242, 541:236, 543:247, 1075:257, 1079:331, 1081:239, 1083:248
    End Content Validation: file:/asurpif_photos_amboycrater_v1.0_20211021_sip_v1.0.tab
```

---

**Comment by qchaupds** [comment]
@jordanpadams Can you help me to understand how this issue is related to issue #390?

The check for each line length was put in for #390 back in September to make sure they were the same.  Now you want the line length to be of different lengths?

**Comment by jordanpadams** [comment]
@qchaupds this is a lower priority for the time being, but my biggest concern here is why it cares about .tab files? We should not be keying off of the filename suffix, instead we should key off of the actual product type. For Collections and SIPs, we should treat these almost exactly the same as `Table_Delimited`

**Comment by jpl-jengelke** [comment]
This passes tests with validate 2.2.0-SNAPSHOT with the error resolved.
