### ISSUE TITLE
Refactor content validation to more robustly handle intermingled Headers

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#425]
## 💪 Motivation
...so that we can ensure files with Header / Table / Header / Table will validate successfully (for example).

## 📖 Additional Details

* Follow on to https://github.com/NASA-PDS/validate/issues/416.
* and discussion that started here: https://github.com/NASA-PDS/validate/pull/420#discussion_r734125186

We need to refactor the TableDataContentValidationRule class (and possibly ArrayDataContentValidationRule class as well) per the following identified issues:
1. the logic appears to be assuming that all Headers objects will come before Table objects (and I'm sure Arrays for that matter), but that is not true. They can be intermingled throughout `<File_Area_Observational>` (after `<File>`). See the [PDS4 IM here spec](https://pds.nasa.gov/datastandards/documents/im/v1/index_1G00.html#class_pds_file_area_observational) for more details.
2. solution from https://github.com/NASA-PDS/validate/pull/420 reads the XML label like it is a text file, which seems very dangerous to me (as became apparent in needing to pull out comments from the file). Wherever possible, we should parse XML as an object into Java for more robust access.

## Proposed Solution
Refactor the content validation classes and pds4 jparser to "walk" through all the objects within `<File_Area_Observational>`, and based on the identified object, perform the necessary validation. e.g.

Given a `<File_Area_Observational>` like:

```
<File>
...
</File>
<Header>
</Header>
<Table_Character>
</Table_Character>
<Header>
</Header>
<Table_Character>
</Table_Character>
```

The software would do something like:
```
for obj in fileAreaObservationalObjects
   if obj is Header
      checkHeader
  elif obj is Table_Character
      checkTableCharacter
  elif obj is Table_Binary
      checkTableBinary
...
```

## ⚖️ Acceptance Criteria
**Given** a label with intermingled objects as noted above, but with invalid offsets
**When I perform** validation with content validation enabled
**Then I expect** validate to throw an error about invalid offsets

**Given** a label with intermingled objects as noted above, and valid
**When I perform** validation with content validation enabled
**Then I expect** validate to complete successfully with no errors

## Test Data
* See https://github.com/NASA-PDS/validate/issues/361#issuecomment-951643479 for array test data
* See https://github.com/NASA-PDS/validate/issues/416 for table

**Comment by rchenatjpl** [comment]
I hope this is the right place, but can we improve the error message? For the attached:
% validate -t ZiWei_boulder_data.xml
[chop]
      ERROR  [error.table.fields_mismatch]   table 1: The table offset 0 for object 'null' is invalid.  The previously defined object ends at byte 331

The Table_Delimited has no name, hence the null, I think. I hope validate uses:
- name
- if no name, local_identifier
- if no name and no local_identifier, maybe something like "Table_Delimited with offset 0"
[Archive.zip](https://github.com/NASA-PDS/validate/files/7456848/Archive.zip)

**Comment by jordanpadams** [comment]
thanks @rchenatjpl. moved that to a new issue: https://github.com/NASA-PDS/validate/issues/436

**Comment by jimmie** [comment]
Trying to continue as best as possible, waiting for input from Michael Cayanan...

**Comment by jordanpadams** [comment]
per @jordanpadams significant rewrite in work, hope to be done by end of week

**Comment by jpl-jengelke** [comment]
Data rollup ... 
[425-480-data.zip](https://github.com/NASA-PDS/validate/files/9953882/425-480-data.zip)

**Comment by miguelp1986** [comment]
Hi @jordanpadams this issue has the i&t.done label but it's still labeled as needs testing on RDD 13.1. Does this still need to be tested?
