### ISSUE TITLE
Product referential integrity check should WARN about collection but wrongly WARNs about bundle

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS-Incubator/validate#437]
In the attached bundle, 4 external context products get referred to by:
YES Product_Observational
NO Product_Collection
YES Product_Bunde
However, validate WARNs about the missing references when checking the bundle not the collection:
% validate -R pds4.bundle -t m2
PDS Validate Tool Report
Configuration:
   Version                       2.2.0-SNAPSHOT
   Date                          2021-11-02T08:22:57Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/m2/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/m2/bundle_moon_lro_lroc_boulderdata_watkins_2018.xml
        1 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/m2/data/ZiWei_boulder_data.xml
        2 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/m2/data/AREA_Camelot_1radii.xml
        3 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/m2/data/collection.xml
        4 product validation(s) completed
PDS4 Bundle Level Validation Results
  PASS: file:/Users/rchen/Desktop/m2/data/collection.xml
        1 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/m2/bundle_moon_lro_lroc_boulderdata_watkins_2018.xml
      WARNING  [warning.integrity.missing_context_reference]   This file should reference 'urn:nasa:pds:context:investigation:mission.lunar_reconnaissance_orbiter' because its child product with LIDVID urn:nasa:pds:moon_lro_lroc_boulderdata_watkins_2018:data:geocsv.area_camelot_1radii::1.0 references it.
      WARNING  [warning.integrity.missing_context_reference]   This file should reference 'urn:nasa:pds:context:instrument_host:spacecraft.lro' because its child product with LIDVID urn:nasa:pds:moon_lro_lroc_boulderdata_watkins_2018:data:geocsv.area_camelot_1radii::1.0 references it.
      WARNING  [warning.integrity.missing_context_reference]   This file should reference 'urn:nasa:pds:context:instrument:lroc.lro' because its child product with LIDVID urn:nasa:pds:moon_lro_lroc_boulderdata_watkins_2018:data:geocsv.area_camelot_1radii::1.0 references it.
      WARNING  [warning.integrity.missing_context_reference]   This file should reference 'urn:nasa:pds:context:target:satellite.earth.moon' because its child product with LIDVID urn:nasa:pds:moon_lro_lroc_boulderdata_watkins_2018:data:geocsv.area_camelot_1radii::1.0 references it.
        2 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/m2/data/ZiWei_boulder_data.xml
        3 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/m2/data/AREA_Camelot_1radii.xml
        4 integrity check(s) completed
Summary:
  0 error(s)
  4 warning(s)
  Product Validation Summary:
    4          product(s) passed
    0          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    4          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    4            warning.integrity.missing_context_reference
End of Report
Completed execution in 6528 ms
[m2.zip](https://github.com/NASA-PDS/validate/files/7458989/m2.zip)

## Related Requirements
🦄 #69

**Comment by jordanpadams** [comment]
Closing as invalid. Reverted #69
