### ISSUE TITLE
Validate throws "file separator" error processing supplemental PNG file

### ISSUE THREAD

**Issue by benjhirsch** [NASA-PDS-Incubator/validate#448]
## 🐛 Describe the bug
Validate throws the error ERROR  [error.validation.internal_error]   Error occurred while processing PNG file content for png_test.png: isPNG:The path does not contain a file separator /C:/Users/Ben/Desktop/png_test.png

## 📜 To Reproduce
1. Run validate on provided sample files.
2. See Validate Tool report.

## 🕵️ Expected behavior
I expected no error at all, because Validate seems to be able to build the path to the PNG correctly. The error message even prints the file name with file separators present.

## 📚 Version of Software Used
Version 2.1.0
Error does not appear using Version 1.22.1

## 🩺 Test Data / Additional context
[png_test.zip](https://github.com/NASA-PDS/validate/files/7620019/png_test.zip)

## 🖥 System Info
 - OS: Windows 10

---

**Comment by jordanpadams** [comment]
@benjhirsch I believe this bug has been fixed per #438 . we plan to tag a new release of validate soon. in the meantime, you can use the latest dev release here: https://github.com/NASA-PDS/validate/releases/tag/v2.2.0-SNAPSHOT . Let us know if you are still seeing this issue.
