### ISSUE TITLE
Validate should not check PDF/A validity if content validation is disabled

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#453]
## 🐛 Describe the bug

When I execute validate with `--skip-content-validation` flag, it still throws an invalid PDF/A warning:

```
  PASS: file:/data/pds4/test-data/registry/lab.hydrocarbon_spectraV1/document/h2205k292k.xml
      WARNING  [warning.pdf.file.not_pdfa_compliant]   file:/data/pds4/test-data/registry/lab.hydrocarbon_spectraV1/document/h2205k292k.pdf is not valid PDF/A file or does not exist
        56 product validation(s) completed
```

## 📜 To Reproduce
```
validate -R pds4.bundle $TEST_DATA_HOME/registry/lab.hydrocarbon_spectraV1/bundle.lab.hydrocarbon_spectra.xml --skip-content-validation
```

## 🕵️ Expected behavior

Validate would skip trying to check validity of the PDF because we are disabling content validation.

## 📚 Version of Software Used

2.0.7, 2.2.0-SNAPSHOT

## 🩺 Test Data / Additional context

`pds-dev3:$TEST_DATA_HOME/registry/lab.hydrocarbon_spectraV1/`

---

**Comment by jordanpadams** [comment]
Deferring from this build since we are running behind schedule

**Comment by miguelp1986** [comment]
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4308201
