### ISSUE TITLE
Validate is reporting an "Uncaught exception while validating" error on Windows

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS-Incubator/validate#464]
## 🐛 Describe the bug
Validate is reporting an internal error for a text file: "Uncaught exception while validating: null"
This error is not reported using older versions of Validate, and we don't see anything wrong with the file.

## 📜 To Reproduce
Run validate on the attached files: validate validate_bug\ -R pds4.folder -r validate_report.txt

## 🕵️ Expected behavior
I don't expect to see the error.

## 📚 Version of Software Used
V2.1.3

## 🩺 Test Data / Additional context
[validate_bug.zip](https://github.com/NASA-PDS/validate/files/7755815/validate_bug.zip)
[validate_report.txt](https://github.com/NASA-PDS/validate/files/7755817/validate_report.txt)

##  🏞Screenshots
![command_line_errors](https://user-images.githubusercontent.com/74932981/146942635-be6341b7-525a-4604-ad5b-3a0f89878864.png)

## 🖥 System Info
OS: Windows 10

---

**Comment by jordanpadams** [comment]
@jennifergward I was able to replicate this problem. This looks to be a windows-specific bug with how we were splitting file paths. Should have a fix merged and released before the end of the calendar year.
