### ISSUE TITLE
Validate content validation does not handle properly special_constants and field_statistics when they both appear

### ISSUE THREAD

**Issue by edguinness** [NASA-PDS-Incubator/validate#469]
## 🐛 Describe the bug
Content validation on a collection that have both Special_Constants and Field_Statistics defined for an ASCII table file throw errors when a special constant appears.. See below for an example of one of the field definitions. Content validation is throwing errors for any case where the value is -9998 or -9999 because these are outside the min/max range. The label is valid according to the Information Model. Therefore, it seems that Validate should not throw an error for this.

        <Field_Character>
          <name>clat</name>
          <field_number>25</field_number>
          <field_location unit="byte">263</field_location>
          <data_type>ASCII_Real</data_type>
          <field_length unit="byte">9</field_length>
          <description>Latitude of FOV center (deg). Undefined if off
                     planet. Uses ellipsoidal moon approximation as described in Section 2.4.3 of the RDR SIS.
                     -90.00000 to 90.00000</description>
          <Special_Constants>
            <invalid_constant>-9998</invalid_constant>
            <unknown_constant>-9999</unknown_constant>
          </Special_Constants>
          <Field_Statistics>
            <maximum>74.09426</maximum>
            <minimum>46.73149</minimum>
          </Field_Statistics>
        </Field_Character>

## 🕵️ Expected behavior
Properly allow special constants when outside the specified min/max range noted in field_statistics.

## 📚 Version of Software Used
Validate 2.0.7 and 1.24.0 yield the same results.

## 🖥 System Info
Windows

## Test Data

[201401031400_rdr.xml.txt](https://github.com/NASA-PDS/validate/files/8016970/201401031400_rdr.xml.txt)
[201401031400_rdr.zip](https://github.com/NASA-PDS/validate/files/8016971/201401031400_rdr.zip)

---

## ⚙️ Engineering Details
I am pretty sure we just need to switch the ordering of these checks.

**Comment by edguinness** [comment]
@jordanpadams Does your analysis above mean that use of both special_constants and field_statistics is valid and that the tool will be updated to fix this in the next release? I would like to know if our label design is OK or needs to be revised. It is for LRO migration, which is supposed to be completed by end of September this year. I am sorry that I am not up on the notation in Github.

**Comment by jordanpadams** [comment]
@edguinness yes. I believe these should be valid, but the logic for checking special constants vs. field statistics needs to be flipped in validate.

**Comment by edguinness** [comment]
@jordanpadams Thanks!

**Comment by jordanpadams** [comment]
@tdddblog with your 1 day per week on Validate, let's start with this one. we can talk about this at one of the daily validate stand-ups either later this week or next week
