### ISSUE TITLE
Validate can't find files in directory specified by <directory_path_name>

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS-Incubator/validate#474]
## 🐛 Describe the bug
I'm running validate on a label that refers to images located in a subdirectory. The label specifies the <file_name> and the <directory_path_name>, but validate seems to be skipping the <directory_path_name> when it's looking for the images and gives a "The system cannot find the file specified" error. Older version of validate do not give this error.

## 📜 To Reproduce
Run validate on the attached folder: validate document_rise\ -R pds4.folder -r validate_report.txt

## 🕵️ Expected behavior
I expect validate to look in document_rise\RISE_InSight_SIS_Raw_files\ for the images instead of document_rise\, as it seems to be doing in the validation report.

## 📚 Version of Software Used
V2.1.4

## 🩺 Test Data / Additional context
[document_rise.zip](https://github.com/NASA-PDS/validate/files/7979126/document_rise.zip)
[validate_report.txt](https://github.com/NASA-PDS/validate/files/7979127/validate_report.txt)

## 🖥 System Info
OS: Windows 10

---

## ⚙️ Engineering Details
Looks like this issue is related to an issue with handling of the file path. should re-work this to use url objects.

**Comment by jordanpadams** [comment]
@jennifergward noted this bug and we will take a look

**Comment by jordanpadams** [comment]
resolved per https://github.com/NASA-PDS/validate/pull/579

**Comment by miguelp1986** [comment]
testrail case: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/cases/view/1271034
