### ISSUE TITLE
Validate crashes on invalid # of records, and spurious file left behind

### ISSUE THREAD

**Issue by rgdeen** [NASA-PDS-Incubator/validate#475]
When given a collection label with this in the inventory section:

      <records>#records#</records>

validate crashes with the trace below.  Putting a valid number in there fixes it.

mipldevlinux13% /project/m20/rgd/pds4/validate/validate-2.1.4/bin//validate -R pds4.bundle -target bundle.xml --report-file ../bundle.xml.valrpt --schematron /project/m20/rgd/pds4/validate/dd//*.sch --schema /project/m20/rgd/pds4/validate/dd//*.xsd --skip-context-validation
.java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule$1.run(LabelInFolderRule.java:151)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataContentValidationRule.java:951)
	... 11 more
Completed execution in 34447 ms

mipldevlinux13% 

----

Separately, I have a PDF file that is not PDF/A.  It puts this file in my bundle top-level dir:

PLACES_M20_PDS_SIS.pdf.1b.error.csv

which also happens to be the current dir when invoking validate.  I guess this provides useful information (maybe)... but having it appear inside the bundle structure is somewhat problematic.

### I&T
TestRail Test ID: T8681187

**Comment by al-niessner** [comment]
See #658 as it contradicts this issue.

**Comment by jordanpadams** [comment]
This can be closed. Software no longer crashes:

```
PDS Validate Tool Report

Configuration:
   Version                       3.4.0-SNAPSHOT
   Date                          2023-10-03T12:29:00Z

Parameters:
   Targets                       [file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github17/delimited_table_good.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/jpadams/proj/pds/pdsen/workspace/validate/validate-3.4.0-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  FAIL: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github17/delimited_table_good.xml
      ERROR  [error.label.schema]   line 115, 16: cvc-pattern-valid: Value '#records#' is not facet-valid with respect to pattern '[0-9]+' for type 'records'.
      ERROR  [error.label.schema]   line 115, 16: cvc-type.3.1.3: The value '#records#' of element 'records' is not valid.
      ERROR  [error.label.context_ref_not_found]   line 43: 'Context product not found: urn:esa:psa:context:investigation:mission.test
      ERROR  [error.label.context_ref_not_found]   line 53: 'Context product not found: urn:esa:psa:context:instrument_host:spacecraft.test
      ERROR  [error.label.context_ref_not_found]   line 62: 'Context product not found: urn:esa:psa:context:instrument:test.spacecraft
      ERROR  [error.table.bad_field_read]   line 1: Data Object #1 (Identifier Not Specified): Cannot invoke "java.math.BigInteger.longValueExact()" because the return value of "gov.nasa.arc.pds.xml.generated.TableDelimited.getRecords()" is null
        1 product validation(s) completed

Summary:

  6 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    3            error.label.context_ref_not_found
    2            error.label.schema
    1            error.table.bad_field_read

End of Report
Completed execution in 5588 ms
```
