### ISSUE TITLE
As a user, I want to check that are no duplicate LIDs/LIDVIDs in a File_Area_Inventory

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#476]
## 💪 Motivation
...so that we make sure the collections are valid

## ⚖️ Acceptance Criteria
**Given** a collection with inventory with a duplicate LIDVID included
**When I perform** validation of the collection product on it's own (-R pds4.label)
**Then I expect** validate to throw an error `error.inventory.duplicate_identifier` with message "Duplicate LIDVIDs identified in inventory `<lidvid here>`"

**Given** a bundle with a collection with inventory with a duplicate LIDVID included
**When I perform** validation of the bundle with the invalid collection included (-R pds4.bundle)
**Then I expect** validate to throw an error `error.inventory.duplicate_identifier` with message "Duplicate LIDVIDs identified in inventory `<lidvid here>`"

**Given** a bundle with a collection with inventory with a duplicate LIDVID included
**When I perform** validation of the bundle with the invalid collection included (-R pds4.collection)
**Then I expect** validate to throw an error `error.inventory.duplicate_identifier` with message "Duplicate LIDVIDs identified in inventory `<lidvid here>`"

**Given** a bundle with a collection with inventory with a duplicate LID (secondary reference) included
**When I perform** validation of the collection product on it's own (-R pds4.label)
**Then I expect** validate to throw an error `error.inventory.duplicate_identifier` with message "Duplicate LIDs identified in inventory `<lid here>`"

**Given** a bundle with a collection with inventory with a duplicate LID (secondary reference) included
**When I perform** validation of the bundle with the invalid collection included (-R pds4.bundle)
**Then I expect** validate to throw an error `error.inventory.duplicate_identifier` with message "Duplicate LIDs identified in inventory `<lid here>`"

**Given** a bundle with a collection with inventory with a duplicate LID (secondary reference) included
**When I perform** validation of the bundle with the invalid collection included (-R pds4.collection)
**Then I expect** validate to throw an error `error.inventory.duplicate_identifier` with message "Duplicate LIDs identified in inventory `<lid here>`"

## ⚙️ Engineering Details

[collection_lab.hydrocarbon_spectra_data_inventory.csv](https://github.com/NASA-PDS/validate/files/8008295/collection_lab.hydrocarbon_spectra_data_inventory.csv)
[collection_lab.hydrocarbon_spectra_data.xml.txt](https://github.com/NASA-PDS/validate/files/8008297/collection_lab.hydrocarbon_spectra_data.xml.txt)

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

We seem to have a problem with fulfilling the requirements of this issue. I have installed a check for duplicate LIDVIDs that work with `-R pds4.collection` but not `-R pds4.label`. The reason is because the inventory is checked in CollectionReferentialIntegrityRule. The rule is only in the pds4.collection chain and not in the label chain. Is every Inventory table always part of a collection so the check can be moved to TableValidator or can products other than a collection have an Inventory table? When run as a label, the references are not checked so the same passes. When run as a collection, there are 247 errors of missing references.

Do you want to only check as a collection or do you want the check as a label? If checked as a label, then need to check product type in the label and do this check for bundle and collection as well. It seems icky to do such a check in label and I am not sure it is possible but it is the only choice.

Please let me know how you want to proceed.

**Comment by jordanpadams** [comment]
@al-niessner I think you can move this to TableValidator. [Per the IM Spec](https://pds.nasa.gov/datastandards/documents/im/v1/index_1J00.html#16.4%C2%A0%C2%A0class_pds_file_area_inventory), `The File Area Inventory class describes a file and an inventory consisting of references to members.`, so even if this were to be used by some other product in the future, if it is a list of references to members, it should not contain duplicates.

**Comment by jordanpadams** [comment]
@al-niessner I updated the story and the acceptance criteria to hopefully be more explicit. we also need to include checks for duplicate LIDs within the inventory.

**Comment by al-niessner** [comment]
@jordanpadams 

When you say duplicate LIDs do you mean:
1. foo:bar::1.0 and foo:bar::2.0 are duplicates of foo:bar
2. foo:bar::1.0 and foo:bar::2.0 with 2.0 being the duplicate to foo:bar
3. just LID to LID duplicates such that there are not duplicates with foo:bar::1.0, foo:bar::2.0, and foo:bar

I am just borrowing a bundle from another test, which is less than perfect but workable. If that is not sufficient then please provide a bundle to test.

**Comment by jordanpadams** [comment]
only foo:bar and foo:bar are duplicates.

**Comment by jordanpadams** [comment]
@al-niessner ☝️

**Comment by al-niessner** [comment]
@jordanpadams 

How do you want duplicate checking done with respect to `--skip-content-validation`?

Another oddity. Moving it to table validation means that `--skip-content-validation` will prevent the error from triggering. Right now, in the `-R pds4.collection` the check is done despite `--skip-content-validation` along with other content validation like missing references (it had to read the file to know this which means it is validating content). It would be weird to get missing references but not duplicates is skip is given. I am moving forward with always process inventory table for duplicates despite skip. Let me know your choice.

**Comment by jordanpadams** [comment]
@al-niessner that approach sounds fine with me

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/validate/pull/645
