### ISSUE TITLE
Validate does not calculate overlaps correctly when Header is not first object in file

### ISSUE THREAD

**Issue by radiosci** [NASA-PDS-Incubator/validate#480]
## 🐛 Describe the bug
In a file with Table_Character1 + Header + Table_Character2, Validate reports that Table_Character1 cannot have offset 0 because there is already an object with length equal to Header in front of it.

## 📜 To Reproduce
1. Unzip and untar attached file header_problem.tar.gz
2. Run Validate on test.xml
3. See error:
 FAIL: file:/Users/rsimpson/Data/DAWN/dawn-rss-raw-vesta/calib-wea/wea/test.xml
    Begin Content Validation: file:/Users/rsimpson/Data/DAWN/dawn-rss-raw-vesta/calib-wea/wea/test.tab
      ERROR  [error.table.fields_mismatch]   table 1: The table offset 0 for object 'Identifier Record for Day-of-Year 001 (Block 1)' is invalid.  The previously defined object ends at byte 180
    End Content Validation: file:/Users/rsimpson/Data/DAWN/dawn-rss-raw-vesta/calib-wea/wea/test.tab
        1 product validation(s) completed

Commenting out the Header definition in the label makes the error go away.  Changing  Header.object_length  to  'nnn'  changes the error message to "The previously defined object ends at byte nnn".
Error does not seem to depend on IM.  I am trying to validate data using IM 1.13.0.0; but I also got errors when I changed to IM 1.16.0.0.

[header_problem.tar.gz](https://github.com/NASA-PDS/validate/files/8150712/header_problem.tar.gz)

## 🕵️ Expected behavior
No error should be reported

## 📚 Version of Software Used
validate 2.1.4

## 🩺 Test Data / Additional context
See attached header_problem.tar.gz

## 🖥 System Info
 - Mac OS 12.0.1
 - Safari 15.1 (17612.2.9.1.20)

---

**Comment by jordanpadams** [comment]
@radiosci agreed. I believe this is tightly coupled with #425 . will keep this open for additional test data

**Comment by radiosci** [comment]
Yes; I did not see #425 before I submitted #480.  They appear to address the same issue.  In my case Header is associate with Table_Character2; but Validate calculates physical locations in such a way that Header seems to be located in front of Table_Character1, thereby triggering a mismatch error.

**Comment by miguelp1986** [comment]
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4206246
