### ISSUE TITLE
As a user, I want to validate labels/bundles/collections using the LBLX file extension

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#482]
## 💪 Motivation
...so that I can support new standard update per CCB-260.

## 📖 Additional Details

* [CCB-260.pdf](https://github.com/NASA-PDS/validate/files/8164947/CCB-260.pdf)
* NOTE: This requirement does not include intermingled XML/LBLX across collections. that will be included in follow on ticket #522

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## ⚙️ Engineering Details

2 ideas for design:
- [x] create 1 new flag to specify label file extension
  1. specify label file extension `--extension [xml,lblx]. defaults to xml`
- [x] if `xml`, crawl for `.xml` files
- [x] if `lblx`, crawl for `.lblx` files,

Some examples:
```
# Crawl bundle, validate XML labels
validate -R pds4.bundle /path/to/bundle.xml --extension xml

# Crawl bundle, validate LBLX labels
validate -R pds4.bundle /path/to/bundle.lblx --extension lblx
```

**Comment by jordanpadams** [comment]
@fran-vallejo LBLX should now be supported in validate using the `-e` or `--extension` flag. feel free to test it out and let me know how it goes. https://github.com/NASA-PDS/validate/releases/tag/v2.2.4-SNAPSHOT

**Comment by jpl-jengelke** [comment]
> @fran-vallejo LBLX should now be supported in validate using the `-e` or `--extension` flag. 

Version `2.4.0-SNAPSHOT` does not respond to the extended `--extension` flag. It uses `--label-extension` instead. 
```
 -e,--label-extension <xml|lblx>         Specify file extension for the labels
                                         files. Default: xml. NOTE: Support for
                                         intermingled bundles where collections
                                         have differing label file extensions is
                                         not yet supported.
```
