### ISSUE TITLE
Validate fails on hidden system files

### ISSUE THREAD

**Issue by jpl-jengelke** [NASA-PDS-Incubator/validate#486]
## 🐛 Describe the bug identified during I&T
Hidden system files that are auto-generated, like .DS_Store, cause validate to fail. 
(Is this by design? Should validate be looking at hidden files? Should it be looking at hidden files if they are not specified in the configurations? Should it be filtering out specifically named system files for different platforms?)

## 🥼 Related Test Case(s)
This appears unrelated to any test case. It was exposed during testing of #421.

## 🔁 : Related issues
N/A

---

## ➕ Additional Details
On Mac OS (or perhaps other systems), browse into a bundle directory. By default Mac OS automatically creates a file named `.DS_Store`. Execute validate on the bundle directory. It fails with an error caused by seeing the hidden OS file.

### 📜 To Reproduce
1. Download and install validate 2.2.0. Download test data at https://github.com/NASA-PDS/validate/tree/main/src/test/resources/github421 
2. Open the test data directories in Mac OS GUI -- 'val421', for instance. Verify an OS file was generated with `find . -type f -name ".DS_Store"`
4. Execute `validate -R pds4.bundle -t val421`
5. Note errors related to `error.file.name_has_invalid_characters`

### 🕵️ Expected behavior
Validate should ignore hidden OS files (possibly all hidden files). 

### 📚 Version of Software Used
Validate 2.2.0 (April 7, 2022)

### 🩺 Test Data / Additional context
N/A

###  🏞Screenshots
```
computer:github421 johnengelke$ find . -type f -name ".DS_Store"
./.DS_Store
./val421/.DS_Store
computer:github421 johnengelke$ validate -R pds4.bundle -t val421

PDS Validate Tool Report

Configuration:
   Version                       2.2.0
   Date                          2022-04-14T15:17:52Z

Parameters:
   Targets                       [file:/pds/validate/src/test/resources/github421/val421/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /sourcecode/source/pds/validate-latest/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/pds/validate/src/test/resources/github421/val421/bundle_moon_lro_lroc_boulderdata_watkins_2018.xml
        1 product validation(s) completed

  PASS: file:/pds/validate/src/test/resources/github421/val421/document/collection_document_inventory.xml
        2 product validation(s) completed

  PASS: file:/pds/validate/src/test/resources/github421/val421/document/watkins_2018_boulderdata_archive_description.xml
        3 product validation(s) completed


PDS4 Bundle Level Validation Results

  PASS: file:/pds/validate/src/test/resources/github421/val421/document/collection_document_inventory.xml
        1 integrity check(s) completed

  FAIL: file:/pds/validate/src/test/resources/github421/val421/.DS_Store
      ERROR  [error.file.name_has_invalid_characters]   File name uses invalid character
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        2 integrity check(s) completed

  PASS: file:/pds/validate/src/test/resources/github421/val421/bundle_moon_lro_lroc_boulderdata_watkins_2018.xml
        3 integrity check(s) completed

  PASS: file:/pds/validate/src/test/resources/github421/val421/document/watkins_2018_boulderdata_archive_description.xml
        4 integrity check(s) completed

Summary:

  1 error(s)
  1 warning(s)

  Product Validation Summary:
    3          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    3          check(s) passed
    1          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.file.name_has_invalid_characters
    1            warning.file.not_referenced_in_label

End of Report
Completed execution in 7467 ms

computer:github421 johnengelke$
```

### 🖥 System Info
 - OS: Mac OS 11.6.5
 - Browser N/A
 - Version Validate 2.2.0

---

**Comment by jordanpadams** [comment]
@jpl-jengelke this is actually invalid per the PDS Standards Reference. Not sure how .DS_Store files get there, but if it is in the zip/tar.gz we provide, we should probably figure out how to not include those.

<img width="1151" alt="Screen Shot 2022-04-14 at 9 49 26 AM" src="https://user-images.githubusercontent.com/33492486/163436288-104a0ff0-0fdc-4493-9990-cda9cd6595a8.png">
