### ISSUE TITLE
Validate is not reporting expected WARNING for 'warning.integrity.missing_context_reference'

### ISSUE THREAD

**Issue by jpl-jengelke** [NASA-PDS-Incubator/validate#492]
## 🐛 Describe the bug identified during I&T
A warning is expected where a bundle.xml lacks a lid_reference to something below it. Ticket [validate#421](https://github.com/NASA-PDS/validate/issues/421) is reported to improve that warning message. The warning does not show up at all now. 

No WARNING is issued at all that says, “WARNING [warning.integrity.missing_context_reference]”.

## 🥼 Related Test Case(s)
B12.1/VAL.18: https://github.com/NASA-PDS/validate/issues/421
https://github.com/NASA-PDS/validate/issues/69

## 🔁 : Related issues
https://github.com/NASA-PDS/validate/issues/69

---

### 📜 To Reproduce
1. Run ‘validate -R pds4.bundle -t <bundle_dir>’ separately with the four datasets provided. 
 

### 🕵️ Expected behavior
Note that the warning reads as follows: ‘WARNING [warning.integrity.missing_context_reference] This file should reference 'urn:nasa:pds:context:investigation:mission.lunar_reconnaissance_orbiter' because its child product with LIDVID '...:document:watkins_2018_boulderdata_archive_description::1.0' references it.’

### 📚 Version of Software Used
`validate`-2.2.0

### 🩺 Test Data / Additional context

[test data](https://github.com/NASA-PDS/validate/tree/main/src/test/resources/github421)

### 🖥 System Info
 - OS: Mac OS X Big Sur 11.6.5
 - Browser N/A
 - Version N/A

---

**Comment by jordanpadams** [comment]
@jpl-jengelke apologies for the confusion here. #421 was one of many issues identified with the initial attempt at #69, which was ultimately reverted for the time being, and will be looked at again in the future.

you can ignore testing #421
