### ISSUE TITLE
Improve Content Validation Performance through Spot Checking

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#498]
## 💡 Description

See sub-tasks for more details

**Comment by jordanpadams** [comment]
📆 July status: Start delayed at least one sprint due to delays in other enhancements / bug fixes.

**Comment by jordanpadams** [comment]
📆 August status: Delayed an additional sprint due to other delays. Looking to squeeze in last minute into build.

**Comment by jordanpadams** [comment]
📆 Sept status: will be deferred from B13.0. this is an important task to get into B13.0 but nothing we can do. will march forward and tag a point build once the task has completed.

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Is this and #1 the same - no sub tasks on ticket?

**Comment by jordanpadams** [comment]
yes they are.

do you have ZenHub extension installed to see the sub-tasks for this Epic?

https://www.zenhub.com/extension

**Comment by jordanpadams** [comment]
@al-niessner ☝️

**Comment by jordanpadams** [comment]
:calendar: December status: Ahead of schedule. PR in review

**Comment by jordanpadams** [comment]
📆 January status: Delayed one sprint to fix regression introduced in other improvement. No impact on delivery anticipated

**Comment by jordanpadams** [comment]
Done on 2/10
