### ISSUE TITLE
Validate does not allow `.arch_h` file name/data type

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS-Incubator/validate#500]
## 🐛 Describe the bug

This validate report, [gbo.ast.catalina.survey_v1.0_20220204-validate.txt](https://github.com/NASA-PDS/validate/files/8671667/gbo.ast.catalina.survey_v1.0_20220204-validate.txt), shows that a file ending with `.arch_h` raises `error.table.field_value_data_type_mismatch`. For example:

>       ERROR  [error.table.field_value_data_type_mismatch]   table 0, record 632116, field 2: Value does not match its data type 'ASCII_File_Specification_Name': The filename spec 'G96_20220129_2B_N56033_01_0002.arch_h' does not match the pattern '[A-Za-z0-9]*[A-Za-z0-9-_\.]*[A-Za-z0-9]\.[A-Za-z0-9]+'

I believe this would be fixed by adjusting the regex to `[A-Za-z0-9]*[A-Za-z0-9-_\.]*[A-Za-z0-9]\.[A-Za-z0-9]+[A-Za-z0-9-_\.]*[A-Za-z0-9]`

## 📜 To Reproduce
1. Run validate on the package from https://sbnarchive.psi.edu/pds4/surveys/catalina_extras/sips/fixes/20220204.zip (submitted in https://github.com/NASA-PDS/operations/issues/252)

## 🕵️ Expected behavior
Validate does not raise an error for `.arch_h` file types.

## 📚 Version of Software Used
v2.2.0 and v2.3.0

## 🩺 Test Data / Additional context
Searching Section 6C.1 File Names (page 60) of [PDS Standards Reference 1.17.0](https://pds.nasa.gov/datastandards/documents/sr/current/StdRef_1.17.0.pdf), this file name seems allowed. However, I'm not sure if this is a valid file type/extension as my cursory research has revealed that `.arch` is but nothing about `.arch_h`, and I have no `.arch_h` file to test.

##  🏞Screenshots
N/A

## 🖥 System Info
Irrelevant

---

**Comment by al-niessner** [comment]
Fixed by #636

The test data is too large (65 MByte binary table file) to add to git so cannot add to regression testing.

**Comment by miguelp1986** [comment]
@jordanpadams I do not have access to test data https://sbnarchive.psi.edu/pds4/surveys/catalina_extras/sips/fixes/20220204.zip. Could you please download the data and share it here? Thank you.

**Comment by jordanpadams** [comment]
@miguelp1986 the files should be here: https://pds.nasa.gov/data/pds4/manifests/2022/ . Search for `gbo.ast.catalina.survey_v1.0_20220204`
