### ISSUE TITLE
validate passes confusing message to the command window

### ISSUE THREAD

**Issue by mit3ch** [NASA-PDS-Incubator/validate#503]
## 🐛 Describe the bug
For every data file (*.tab), in the command window validate prints:
"java.io.FileNotFoundException: null\uvis_euv_2005_159_solar_time_series_ingress.tab (The system cannot find the path specified)"

However, it does complete content validation on every file. I forced an error into the file mentioned above, and validate found it.
## 📜 To Reproduce

I'm running validate from the command line on a windows 10 machine with JRE version 1.8.0_311

My command line entry is:
validate 2022-05-19-becker-solar-occ\cdap2018_becker_saturn_ring_particles_V9 -C .\catalog.xml -R pds4.bundle -v 2 -r becker-bundle_V9-0n.log

I use a catalog file located in the directory from which I am running validate.

## 🕵️ Expected behavior

Not get the message

## 📚 Version of Software Used

2.1.4
## 🩺 Test Data / Additional context

Let me know if you want some.
##  🏞Screenshots

[validate-print-screen.txt](https://github.com/NASA-PDS/validate/files/8732231/validate-print-screen.txt)

## 🖥 System Info

---

**Comment by jordanpadams** [comment]
sorry about this @mit3ch . this is a funky Windows thing we are trying to look into. will add this to the top of our list

**Comment by jordanpadams** [comment]
@mit3ch is this bundle online somewhere we could download it?

**Comment by mit3ch** [comment]
I'm not sure this is urgent since validate works correctly anyway. I'd suggest a note somewhere warning that it might occur and perhaps offering a method to verify that validate is working properly(e.g., I added a ASCII character to a numeric field in one file). However, I suspect that a lot of users are like me, and don't review documentation frequently, so you may get repeat reports of this bug from time-to-time.

Mitch

Dr. Mitch Gordon
SETI Institute
Deputy Manager
PDS Ring-Moon Systems Node
276-393-8822
Pronouns: he, him, his

**Comment by mit3ch** [comment]
@jordan try this;

https://drive.google.com/drive/folders/12ThRc4lRmr7MnttKa1rxsrGhc7dLosc6?usp=sharing<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2Fnam11.safelinks.protection.outlook.com%2F%3Furl%3Dhttps*3A*2F*2Fdrive.google.com*2Fdrive*2Ffolders*2F12ThRc4lRmr7MnttKa1rxsrGhc7dLosc6*3Fusp*3Dsharing%26data%3D05*7C01*7Cmgordon*40seti.org*7Ccdaa8478fa824d07618608da39a8a384*7Cdeac5258294749c2a474e8ab151104fb*7C0*7C0*7C637885693759863628*7CUnknown*7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0*3D*7C3000*7C*7C*7C%26sdata%3DETABb*2Bo8goPrILsFQGxf0Siy7BFsw*2FTnF8k5JAMhdfU*3D%26reserved%3D0__%3BJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSU!!D-JDmu3Lc2wo0Jiybg!M_grPSRNkT5D6Boe3UVUuSUyX6DDnGGKXSBRzkHSHTKjwxd-iNeG7NhyPndoacjhrKJB%24&data=05%7C01%7Cmgordon%40seti.org%7Cef9510c30e98496e7f4308da39b49548%7Cdeac5258294749c2a474e8ab151104fb%7C0%7C0%7C637885745034433468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7ieCT%2Fkm1scQPk4f2KO0%2B1i%2B6LlkNLP5zN5Pmxt2AgI%3D&reserved=0>

If you can't access it, I'll move it to another folder. There is a bogus .DS_Store file in the data directory which needs to be removed along with its entry in the checksum manifest.

Mitch

Dr. Mitch Gordon
SETI Institute
Deputy Manager
PDS Ring-Moon Systems Node
276-393-8822
Pronouns: he, him, his

**Comment by jpl-jengelke** [comment]
@jordanpadams: Is there any special catalog file to use to test this bundle?

**Comment by miguelp1986** [comment]
Testrail: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/cases/view/1273419
