### ISSUE TITLE
CRLF/LF checks do not seem to be working as expected for Table_Character

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#508]
## 🐛 Describe the bug

Testing using the test data under `github292/table_character`, the invalid tests do not seem to be executing as expected. Commented out the tests for the time being. Need to investigate.

## 📜 To Reproduce
2 of the github292 cucumber tests were failing and had to be commented out

## 🕵️ Expected behavior

expected failures actually fail

## 📚 Version of Software Used

2.2.0

## 🩺 Test Data / Additional context

see github292 in repo

---

## 🦄 Related requirements
🦄 #292

**Comment by al-niessner** [comment]
Tests have not been commented out since #480
