### ISSUE TITLE
Table_Character not accurately checking field formats

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#511]
Attached are Thomas's files modified:
- the .CSV is chopped to 6 fields so that all data lines are the same length
- stuff irrelevant to this problem is stripped from the .xml
- the Table_Delimited is copied to a Table_Character and modified appropriately. 'diff *.xml' to see
So:
- validate incorrectly flags valid hex values, as Thomas originally pointed out
- validate seemingly ignores field_format for Table_Character but considers it for Table_Delimited
- validate considers data_type for both. If you change a value to something non-hex, an extra error is reported for both
Those are the facts. More is just opinion, and I'm confident you guys know what to do.

There was more little stuff irrelevant to this issue that you would have eventually caught:
- The last dash in title (before "ICO Unknown Activity") was a non-ASCII dash
- No blank space (specifically carriage-returns and spaces) within logical_identifier or lid_reference
- No caps in LIDs either
So (the carriage-return isn't visually showing correctly):
`        <logical_identifier>
           urn:nasa:pds:clipper.ecm:data-register-raw:XXX000XXX_...</...>
should be
        <logical_identifier>urn:nasa:pds:clipper.ecm:data-register-raw:xxx000xxx_...</...>
`

[Archive.zip](https://github.com/NASA-PDS/validate/files/8827612/Archive.zip)

_Originally posted by @rchenatjpl in https://github.com/NASA-PDS/validate/discussions/510#discussioncomment-2874183_

**Comment by tloubrieu-jpl** [comment]
Note from @rsjoyner on this ticket:
I tested the value of “%2x” in <field_format> and it passes validation in O2.  So, it is a bug in Valdiate.
 
                 <Field_Character>
                     <name>LTST</name>
                     <field_number>2</field_number>
                     <field_location unit="byte">5</field_location>
                     <data_type>ASCII_Real</data_type>
                     <field_length unit="byte">5</field_length>
                     <field_format>%2x</field_format>
                     <description>Local True Solar Time</description>
                 </Field_Character>
 
 
Here is the “pattern” that is in the XSD:
 
    <xs:restriction base="pds:ASCII_Short_String_Collapsed">
            <xs:pattern value='%[\+,-]?[0-9]+(\.([0-9]+))?[doxfeEs]'/>
     <xs:minLength value="1"/>
     <xs:maxLength value="255"/>
               </xs:restriction>
 
Let me know if you need more info.
Or, if I missed something…

**Comment by jordanpadams** [comment]
FYI, since the bug is in the actual value in the data file, Oxygen can't catch that since it only checks the label. So it is has to be validate.

**Comment by miguelp1986** [comment]
Testrail: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/cases/view/1273420
