### ISSUE TITLE
validate embedded in an app bundled as a fat-jar raise exception on product validation 

### ISSUE THREAD

**Issue by fran-vallejo** [NASA-PDS-Incubator/validate#516]
Product validation raises an exception when validate runs as part of an application bundled as a fat-jar.

Root cause is validate tries to locate resource **validation-commands.xml** in the system's classpath. This doesn't work when validate is embedded in an application bundled in a fat-jar as the resources are located in a class path created by the application loader, being the only resource in the system class loader the fat-jar itself (but not the jars it contains).  

[Spring boot documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#executable-jar.restrictions) advises against using the system class loader in this kind of apps:
> System classLoader: Launched applications should use Thread.getContextClassLoader() when loading classes (most libraries and frameworks do so by default). Trying to load nested jar classes with ClassLoader.getSystemClassLoader() fails. java.util.Logging always uses the system classloader. For this reason, you should consider a different logging implementation.

validate would require the following modification to run when embedded in another application bundled as a fat-jar.

Update **gov.nasa.pds.tools.validate.ValidationResourceManager** line 38 from: 
`URL commandsURL = ClassLoader.getSystemResource("validation-commands.xml");`
to
`URL commandsURL = Thread.currentThread().getContextClassLoader().getResource("validation-commands.xml");`

## 📚 Version of Software Used
validate 2.1.4

## 🖥 System Info
 - OS: Ubuntu 20.04
 - Version Java 1.8

---

**Comment by jpl-jengelke** [comment]
@jordanpadams or @fran-vallejo: Is there a sample application bundled as a FAT JAR that uses validate as a dependency that can be used to test this? (Otherwise, we may need to write a small app to validate `validate`.)

**Comment by jordanpadams** [comment]
@jpl-jengelke just updated this to skip I&T
