### ISSUE TITLE
As a user, I want to receive an error when no products are found within the validation target

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#524]
## 💪 Motivation
...so that I can ensure validate was executed successfully. Some software or automated processed may see there were no errors reported, when, in reality, no products were processed due to incorrect input arguments/parameters.

## ⚖️ Acceptance Criteria
**Given** a directory with no files with the matching file extension
**When I perform** validate against that folder with the pds4.folder rule (or `-t /path/to/data/*`)
**Then I expect** validate to raise an error that no products were found.

**Comment by jpl-jengelke** [comment]
Test data for 482/524
[testdata.zip](https://github.com/NASA-PDS/validate/files/9969122/testdata.zip)

**Comment by jpl-jengelke** [comment]
Verified fixed in Validate 3.1.0.
