### ISSUE TITLE
Validate reports NaNs in a binary (FITS) file possibly erroneously.

### ISSUE THREAD

**Issue by lylehuber** [NASA-PDS-Incubator/validate#532]
## 🐛 Describe the bug
Validate reports NaNs in a binary (FITS) file possibly erroneously. Inspection of the FITS file with a FITS viewer does not indicate that there are any NaNs at the locations indicated.

## 📚 Version of Software Used
Validate 2.3.0

## 🩺 Test Data / Additional context
Github won't let me load a FITS file apparently. FITS file has been sent to Jordan along with the XML label and the validate report.

[validate_532.zip](https://github.com/NASA-PDS/validate/files/9270291/validate_532.zip)

---

**Comment by jordanpadams** [comment]
@rchenatjpl is there any way you could check this with PDS4 Viewer for us?

**Comment by rchenatjpl** [comment]
PDS4 Viewer: when I choose to View Image, the program refuses with a pop-up that ends with "ValueError: Axis limits cannot be NaN or Inf". When I choose to View Table, all the spots that validate calls out as NaN also show up as NaN (PDS4 Viewer's array indexes start at 0, so the values are 1 lower). I can dig into the bytes if so desired.
![Screen Shot 2022-08-05 at 09 47 47](https://user-images.githubusercontent.com/56557532/183123971-7e31532c-ff62-463a-bea3-e2dc059319a7.png)

**Comment by lylehuber** [comment]
Yeah, I'm going to call into question the validity of the PDS4 Viewer values. They are jumping all over the place from -9e-33 to 0.9 to 8e29 in neighboring pixels! Please verify using a different viewer. FV shows the same pixels all at around 0.003 (or -0.006).

**Comment by lylehuber** [comment]
<img width="1025" alt="Screen Shot 2022-08-05 at 11 15 07 AM" src="https://user-images.githubusercontent.com/36681648/183127954-ee80dddb-c5fe-48d5-a355-e50aa3d41c64.png">

**Comment by rchenatjpl** [comment]
Hi, Lyle, on line 132:
     <data_type>IEEE754MSBSinglle</data_type>
should be
     <data_type>IEEE754MSBDouble</data_type>

**Comment by lylehuber** [comment]
Ah of course. Thought we had told them that...

**Comment by rchenatjpl** [comment]
doh, I am out of practice somehow. I should have picked up on the bouncing values in seconds.

**Comment by jordanpadams** [comment]
@rchenatjpl @lylehuber just to verify, is this still a validate issue or are we ok to close this?

**Comment by rchenatjpl** [comment]
Let's close it.

**Comment by lylehuber** [comment]
Agreed.

**Comment by jordanpadams** [comment]
thanks @rchenatjpl and @lylehuber ! appreciate it
