### ISSUE TITLE
B14.0 Content Validation Improvements: Additional Table Types, Additional File Areas

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#534]
## 💡 Description

See sub-tasks for more details

**Comment by jordanpadams** [comment]
📆 February status: Will be deferred in order to work on other higher priority Registry tasks. Per stakeholder feedback, will include in point build as needed.

**Comment by al-niessner** [comment]
@jordanpadams All sub tasks are closed. I am closing this one but you can reopen it if should not be closed.
