### ISSUE TITLE
validate gives a error.table.bad_field_read error

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS-Incubator/validate#544]
## 🐛 Describe the bug
validate 2.4.0 reading a browse product which previously passed validation gives this error:
```
  FAIL: file:/Users/mbentley/Downloads/TEST_V1/bc_mpo_mag/browse_calibrated/near_earth_commissioning/sc/ob/scf/mag_cal_sc_browse_ob_s2_scf_00000_20181024.xml
      ERROR  [error.table.bad_field_read]   line 0: Cannot invoke "gov.nasa.arc.pds.xml.generated.ObjectLength.getValue()" because the return value of "gov.nasa.arc.pds.xml.generated.EncodedByteStream.getObjectLength()" is null
```

## 📜 To Reproduce
1. validate the attached product

## 🕵️ Expected behavior
Product passes validation

## 📚 Version of Software Used
validate 2.4.0

## 🩺 Test Data / Additional context
[mag_cal_sc_browse_example.zip](https://github.com/NASA-PDS/validate/files/9923230/mag_cal_sc_browse_example.zip)

## 🖥 System Info
 - OS: macOS
 - Browser N/A
 - Version 12.5.1

---

**Comment by msbentley** [comment]
I also get the same results with validate 3.0.0

**Comment by jimmie** [comment]
PR out for review and approval - needed for validate release.

**Comment by nutjob4life** [comment]
Well, even with the newly-released, non-SNAPSHOT `pds4-jparser` version 2.3.0, this error still occurs.

But I'm out of time for today so I'll have to investigate tomorrow.

**Comment by nutjob4life** [comment]
Okay, here's an (interesting?) observation. If I add the indicated line to @msbentley's `mag_cal_sc_browse_ob_s4_scf_00000_20181024.xml` file …
```xml
<Encoded_Image>
    <offset unit="byte">0</offset>
    <object_length unit="byte">12345</object_length> <!-- 👈 this line -->
    <encoding_standard_id>PNG</encoding_standard_id>
</Encoded_Image>
```
… then `validate` works just fine.

So I'm suspecting that `<object_length>` is somehow being marked as "required" when it isn't—or, possibly, it _is_ now required 🤷‍♀️

**Comment by nutjob4life** [comment]
In the file [Label.java](https://github.com/NASA-PDS/pds4-jparser/blob/4bebfa9d098d8ce2ad964bb913fd4036f479d4f8/src/main/java/gov/nasa/pds/label/Label.java#L666) at line 666–669, we have:
```java
    if (stream instanceof EncodedByteStream) {
      EncodedByteStream ebs = (EncodedByteStream) stream;
      size = ebs.getObjectLength().getValue().longValueExact(); // 👈 There's your problem
      offset = ebs.getOffset().getValue().longValueExact();
```
The `getObjectLength()` is returning `null`, so we can't call `getValue()` on it.

However, this code _hasn't changed_ in … well, in a while! So the assumption it's made that it would never be `null` was incorrect for some time.

Looking at the `src/build/resources/schema` files, though, I don't see any place that has `<object_length>` as required (except in `<Parsable_Byte_Stream`>s where `minOccurs="1"`).

So _something else_ has changed. Maybe the "object length" had a default value before?

**Comment by miguelp1986** [comment]
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4212017
