### ISSUE TITLE
Validate 2.4.0/3.0.0 fail with NPE/internal error on certain test cases

### ISSUE THREAD

**Issue by jpl-jengelke** [NASA-PDS-Incubator/validate#545]
## 🐛 Describe the bug identified during I&T
Execute `validate -t testdata/badtype.xml` against the linked dataset used to test pds4-im#499. This will yield both an exception and an internal error. (See attached output, Also, please note an earlier SNAPSHOT of Validate 2.4.0 did not yield this error but the current releases do.)

This error only manifests on this test case so far as others currently appear to not yield the error.

## 🥼 Related Test Case(s)
[pds4-im#499](https://github.com/NASA-PDS/pds4-information-model/issues/499)

## 🔁 : Related issues
These may not be proximately related, but the refactoring preceded the report:
https://github.com/NASA-PDS/validate/issues/425
https://github.com/NASA-PDS/validate/issues/537

---

## ➕ Additional Details
Versions: Java 11, Validate 3.0.0 and Validate 2.4.0
Also, both test commands yield errors:
`validate -t baddata.xml`
`validate -t shouldpass.xml`

### 📜 To Reproduce
Download dataset:
Execute `validate -t baddata.xml` to view error.
Execute `validate -t shouldpass.xml` to view error.

### 🕵️ Expected behavior
No NPE, no internal error. Validation should proceed to notify user of errors/warnings or pass product.

### 📚 Version of Software Used
Validate 2.4.0
Validate 3.0.0

### 🩺 Test Data / Additional context
https://github.com/NASA-PDS/pds4-information-model/files/9952397/testdata.zip

###  🏞Screenshots
Execution log: 
[validate-2.4.0-3.0.0-badtype-fail.txt](https://github.com/NASA-PDS/validate/files/9952438/validate-2.4.0-3.0.0-badtype-fail.txt)

### 🖥 System Info
 - OS: Mac OS X 11.7.1
 - java 11.0.3 2019-04-16 LTS
 - Validate 2.4.0 or 3.0.0
 - GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

---

**Comment by jpl-jengelke** [comment]
@gxtchen @viviant100

**Comment by nutjob4life** [comment]
I wonder if [my fix](https://github.com/NASA-PDS/pds4-jparser/pull/63) for [validate#544](https://github.com/NASA-PDS/validate/issues/544) would also solve this 🤔

**Comment by viviant100** [comment]
Unfortunately we are still seeing the issue with v3.0.2 release.
