### ISSUE TITLE
Validate partially fails regression test on issue 343

### ISSUE THREAD

**Issue by jpl-jengelke** [NASA-PDS-Incubator/validate#552]
## 🐛 Describe the bug identified during I&T
Regression test [validate#343](https://github.com/NASA-PDS/validate/issues/343) partially fails in the regression testing tool. 

- Table name is no longer displayed when provided as an error occurs. (Instead, it's numeric, ala `array 0`.) NOTE: this was the central theme of #343 .
- Similar to #548, errors are announced with `array 0` which seems to differ from earlier iterations that counted starting from 1. 

The capacity to display a provided array name should be restored to fix this ticket.

## 🥼 Related Test Case(s)
UNKNOWN -- This cannot be located in any test reports since ticket closure on July 7, 2021.

## 🔁 : Related issues
https://github.com/NASA-PDS/validate/issues/343
https://github.com/NASA-PDS/validate/pull/370
https://github.com/NASA-PDS/validate/pull/548

---

## ➕ Additional Details
https://pds-jenkins.jpl.nasa.gov/job/console-regression-tests/job/develop/306/console
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4072910

### 📜 To Reproduce
See steps [here](https://pds-jenkins.jpl.nasa.gov/job/console-regression-tests/job/develop/306/console)

### 🕵️ Expected behavior
During a failure, the table/array name is reported instead of a numeric array index, if and when the table/array name is provided in the bundle file.

### 📚 Version of Software Used
Validate 3.0.3

### 🩺 Test Data / Additional context
https://github.jpl.nasa.gov/PDSEN/console-test-tool/tree/develop/datasets/validate/343/testdata

### 🖥 System Info
 - OS: Mac OS X 11.7.1 or Ubuntu-latest (Dockerized)
 - java 11.0.3 2019-04-16 LTS
 - Validate 2.4.0 or 3.0.0
 - GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

---

**Comment by jordanpadams** [comment]
@jpl-jengelke closing this as wontfix. I know the user wants the name, but passing that through the software is a huge pain, and in many files the names are super confusing. will see if this really becomes an issue.

**Comment by jpl-jengelke** [comment]
@jordanpadams Then should we remove #343 from regression tests or just count it as fixed if the array is indexed starting from 1? Maybe unmark #343 as 'required'?

**Comment by jordanpadams** [comment]
@jpl-jengelke yes let's wipe it. thanks
