### ISSUE TITLE
As a user, I want to be able to use validate from a docker container

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#556]
## 🧑‍🔬 User Persona(s)

Data Provider, Node Personnel

## 💪 Motivation
...so that I do not need to install Java in order to run the app.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by ramesh-maddegoda** [comment]
Created the pull request https://github.com/NASA-PDS/validate/pull/580

**Comment by ramesh-maddegoda** [comment]
Incorporated pull request review comments at https://github.com/NASA-PDS/validate/pulls

**Comment by jordanpadams** [comment]
done per #580

**Comment by miguelp1986** [comment]
Testrail: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/cases/view/1864370
