### ISSUE TITLE
Dockerize Validate

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#557]

**Comment by jpl-jengelke** [comment]
BTW, it's running in a container for the regression tests, although I think that's probably a different request.

**Comment by jpl-jengelke** [comment]
Now I actually have it building in a container and unpacking the build to run it. I'm using a sparse checkout (Git 2.25.1+) so the checkout is completed within seconds and does not collect all the test data. Compile is using Maven 3.6.3 and JDK 11 in an Ubuntu 20 LTS container. It's set to do a clean dependency pull on each run so it also tests whether the dependencies actually are available.

**Comment by jordanpadams** [comment]
thanks @jpl-jengelke we are looking to do this with deployed versions only, but a test setup may be an option as well. can you add a link to this Dockerfile?

**Comment by jordanpadams** [comment]
all sub-tasks completed
