### ISSUE TITLE
Validate (latest) fails to compile in new environment

### ISSUE THREAD

**Issue by jpl-jengelke** [NASA-PDS-Incubator/validate#563]
## 🐛 Describe the bug identified during I&T
Validate fails to compile with a bad gateway error on the regression test server. The regression test server compiles the tip of the `validate` repo `main` branch. On each compile it simulates a clean system that has not compiled validate previously. 

## 🥼 Related Test Case(s)
Unknown

## 🔁 : Related issues
N/A

---

## ➕ Additional Details
[See attached compile log file.](https://github.com/NASA-PDS/validate/files/10118979/validate_bad_gateway_20221129.txt)

It's unclear whether this issue is transitory or permanent due to the repository availability of a publicly available OSS dependency. See attached screenshot.

### 📜 To Reproduce
1. Clone or update an existing Validate repository on a local workstation.
2. `cd` into the `validate` directory referenced in item (1).
    1. To test the exact commit causing this issue, execute `git checkout 2922107` (which just happens to be at the tip at this moment.
4. Execute `mkdir -p .tmp`
5. To simulate a clean Maven `.m2` repository build, execute the following command which will build while downloading all dependencies to a local directory named `.tmp`: `mvn -U clean package -DskipTests -Dmaven.repo.local=$PWD/.tmp`

### 🕵️ Expected behavior
The repository builds and packages artifacts successfully with a `BUILD SUCCESS` message.

### 📚 Version of Software Used
Validate commit at tip of `main`: hash `2922107`

### 🩺 Test Data / Additional context
Potential network issue where dependency cannot be downloaded. It appears that the bad gateway message is appearing for all `https://artifactory.openpreservation.org/` URLs.

**NOTE:** This has been tested outside the Lab LAN. It appears to occur on non-proxied networks, also. It also appears when navigating to the URL directly in a browser. 

```
Failed to collect dependencies at org.verapdf:pdfbox-validation-model:jar:1.20.1 -> org.verapdf.pdfbox:pdfbox:jar:2.0.62[m: Failed to read artifact descriptor for org.verapdf.pdfbox:pdfbox:jar:2.0.62: Could not transfer artifact org.verapdf.pdfbox:pdfbox:pom:2.0.62 from/to vera-dev (https://artifactory.openpreservation.org/artifactory/vera-dev): Transfer failed for https://artifactory.openpreservation.org/artifactory/vera-dev/org/verapdf/pdfbox/pdfbox/2.0.62/pdfbox-2.0.62.pom 502 Bad Gateway -> [1m[Help 1]
```

###  🏞Screenshots
![validate_vera_bad_gateway_20221129](https://user-images.githubusercontent.com/52300928/204696235-80ec3e6d-6b72-45f0-872b-ae4cdcfe2e08.png)

### 🖥 System Info
 - OS: Mac OS X 11.7.1 or Ubuntu-latest (Dockerized)
 - java 11.0.3 2019-04-16 LTS
 - Validate 2.4.0 or 3.0.0
 - GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

---

**Comment by jordanpadams** [comment]
@jpl-jengelke closing this as wontfix. looks like this was a random server failure that has been resolved.

see failure of github action here: https://github.com/NASA-PDS/validate/actions/runs/3575921450/attempts/1

and success here: https://github.com/NASA-PDS/validate/actions/runs/3575921450

**Comment by jpl-jengelke** [comment]
@jordanpadams 
> a random server failure that has been resolved
> 
See https://github.com/veraPDF/veraPDF-library/issues/1310#issuecomment-1331885815 .

The regression tests will fail with stuff like this. It was actually a server outage that lasted a couple days that was reported and then fixed. Yes, good to close.
