### ISSUE TITLE
Records mismatch includes invalid record count

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#568]
## 🐛 Describe the bug

Oringally reported by @mit3ch:

When validate returns an error for a records mismatch, it miscalculates the actual number of records. In the attached pair, uvis_euv_2016_288_solar_time_series_egress, validate returns the message:  

>  ERROR  [error.table.records_mismatch]   table 1: Number of records read is not equal to the defined number of records in the label (expected 1322, got 1318). The actual value for the number of records is 1316, so validate's calculated value of 1318 is incorrect

## 🕵️ Expected behavior

Record count correct

## 🖥 System Info

---

## ⚙️ Engineering Details
[insufficient content validation.zip](https://github.com/NASA-PDS/validate/files/9396013/insufficient.content.validation.zip)

**Comment by jordanpadams** [comment]
@mit3ch FYI this functionality has been changed in the latest version of validate, it now does a file size check before trying to read the number of records, so here is the new error message when trying to validate `uvis_euv_2016_288_solar_time_series_egress`:

```
  FAIL: file:/Users/jpadams/Downloads/insufficient.content.validation/uvis_euv_2016_288_solar_time_series_egress.xml
      ERROR  [error.label.table_definition_problem]   line 2: Data Object #2: Cannot read object. Remaining file size: 342160, Expected bytes remaining for object: 343720
        2 product validation(s) completed
```

**Comment by mit3ch** [comment]
Dr. Mitch Gordon
SETI Institute
Deputy Manager
PDS Ring-Moon Systems Node
276-393-8822
Pronouns: he, him, his

**Comment by mit3ch** [comment]
@jordan. I'm sorry, I'm probably missing something, but the new error message seems less clear than the original. At first glance this gives less information to interpret when I'm trying to troubleshoot the label.

**Comment by jordanpadams** [comment]
@mit3ch copy. we will put a new feature request to improve the error message.
