### ISSUE TITLE
Improve error message when file is truncated and cannot be read

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#569]
## 📖 Additional Details

As a follow on to #568, we need to more clearly provide input to a user when a data object is shorter than the remaining file available.

Current error message:
```
  FAIL: file:/Users/jpadams/Downloads/insufficient.content.validation/uvis_euv_2016_288_solar_time_series_egress.xml
      ERROR  [error.label.table_definition_problem]   line 2: Data Object #2: Cannot read object. Remaining file size: 342160, Expected bytes remaining for object: 343720
        2 product validation(s) completed
```

Maybe not how many rows are expected to be read and not that the file is truncated and only X number of records can be read (this can be done using a simple calculation versus actually trying to read the data).

**Comment by jordanpadams** [comment]
@mit3ch how is this error message?

```
FAIL: file:/Users/jpadams/Downloads/insufficient.content.validation/uvis_euv_2016_288_solar_time_series_egress.xml
      ERROR  [error.label.table_definition_problem]   line 2: Data Object #2 (Identifier Not Specified): Data object is truncated. Expected bytes as defined by label: 343720 (1322 records), Actual bytes remaining in file: 342160 (1316 records)
        1 product validation(s) completed

```

**Comment by mit3ch** [comment]
@jordan, yes, that would be much more useful.

Thanks

Dr. Mitch Gordon
SETI Institute
Deputy Manager
PDS Ring-Moon Systems Node
276-393-8822
Pronouns: he, him, his
