### ISSUE TITLE
validate does not correctly handle field format checks for hex values

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS-Incubator/validate#576]
## 🐛 Describe the bug

The PDS4 IM defines several ASCII data types for unsigned integers in bases other than 10:

ASCII_Numeric_Base2
ASCII_Numeric_Base8
ASCII_Numeric_Base16

with the description

> The ASCII Numeric Basen class indicates an ASCII character representation of a non-negative unsigned integer in base n. [snip] May not be preceded by any sign (+/-) notation.

and the SR (section 4B.1.2) shows that one should be able to specify and validate the field format of these in a POSIX-like syntax.

When testing with hex values and applying a field format:
```xml
        <Field_Delimited>
          <name>Base16</name>
          <field_number>5</field_number>
          <data_type>ASCII_Numeric_Base16</data_type>
          <field_format>%4x</field_format>
        </Field_Delimited>
```
validate complains:

```
ERROR  [error.table.field_value_format_specifier_mismatch]   data object 1, record 1, field 5: The value '0A00' does not match the defined field format specifier 'x': For input string: "A00"
ERROR  [error.table.field_value_format_specifier_mismatch]   data object 1, record 2, field 5: The value 'FFFF' does not match the defined field format specifier 'x': For input string: "FFFF"
ERROR  [error.table.field_value_format_specifier_mismatch]   data object 1, record 3, field 5: The value '10c8' does not match the defined field format specifier 'x': For input string: "10c8"
```
Note that I tried both upper and lower case letters for the hex values.

## 📜 To Reproduce
1. Try to validate the attached product

## 🕵️ Expected behavior
validate fully supports base2/8/16 values.

## 📚 Version of Software Used
validate 3.0.3

## 🩺 Test Data / Additional context
[basen.zip](https://github.com/NASA-PDS/validate/files/10208593/basen.zip)

## 🖥 System Info
 - OS: MacOS
 - Version 12.5.1

---

**Comment by jordanpadams** [comment]
@msbentley sorry for the bug. we will add it to the queue of bug fixes. is this blocking anything critical right now?

**Comment by msbentley** [comment]
Thanks @jordanpadams - no, it's not critical (in fact it only cropped up because of I was making some test products to probe certain aspects of the IM/validate/tools)

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

Cannot replicate. Probably fixed with #511 

```
PDS Validate Tool Report

Configuration:
   Version                       3.1.0-SNAPSHOT
   Date                          2022-12-22T21:59:28Z

Parameters:
   Targets                       [file:/tmp/test/basen_test.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /home/niessner/Projects/PDS/validate/src/main/resources/util/registered_context_products.json



Product Level Validation Results

  FAIL: file:/tmp/test/basen_test.xml
      ERROR  [error.label.context_ref_not_found]   line 37: 'Context product not found: urn:esa:psa:context:investigation:mission.test
      ERROR  [error.label.context_ref_not_found]   line 47: 'Context product not found: urn:esa:psa:context:instrument_host:spacecraft.test
      ERROR  [error.label.context_ref_not_found]   line 56: 'Context product not found: urn:esa:psa:context:instrument:test.test
        1 product validation(s) completed

Summary:

  3 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    3            error.label.context_ref_not_found

End of Report
Completed execution in 4976 ms
```

**Comment by jordanpadams** [comment]
this bug probably fixed by https://github.com/NASA-PDS/validate/issues/511

**Comment by miguelp1986** [comment]
Testrail: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/cases/view/1273425
