### ISSUE TITLE
B13.1 Fix Must-Have Priority Bugs

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#578]

**Comment by al-niessner** [comment]
No checkbox means on hold waiting for a response. Empty checkbox means needs work. Filled checkbox means work is complete.

- [x] #474 
- [x] #499 
- [x] #511 
- #519 
- [x] #529 
- [x] #531 
- [x] #576 

When done here, move to #498

**Comment by al-niessner** [comment]
When done here, move to #498

**Comment by jordanpadams** [comment]
:calendar: December status: Ahead of schedule. Awaiting test data for 1 more bug

**Comment by jordanpadams** [comment]
All must-have bug fixes fixed for this build
