### ISSUE TITLE
Add summary to report to referential integrity execution

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#602]
## 💡 Description

Similar to the current validate output, we need a summary at the end to show an overall summary count of things validated, failed, skipped, etc.

**Comment by al-niessner** [comment]
@jordanpadams 

Nothing is ever is skipped. It passes or fails. The the summary line:

```
12:08:13,229  INFO main CommandLineInterface:process:119 - Completed the reference integrity checks for 46 products and found 257 broken references.
```

Can you give me an example of what you want the summary to be like given you have 3 numbers: references checked or exist, references found (checked + failed), and references missing. Ideally and if the test data set was filled it should read checked 303 checked and 0 failed. Is there ever a case when it is okay to have failures?

**Comment by jordanpadams** [comment]
blocked. awaiting input from @jordanpadams

**Comment by al-niessner** [comment]
Related (not necessary duplicate) to #611

**Comment by jordanpadams** [comment]
@al-niessner for this, if -verbose is enabled, I would like something like:
```
X products processed
X errors
X warnings
```
