### ISSUE TITLE
As a user, I want to validate MP4/H.264 encoded video as observational data

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#604]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Archive Manager

### 💪 Motivation

...so that I the encoded video is valid and meets the standards outlined by ISO standard for MP4/H.264.

### 📖 Additional Details

See [CCB-325](https://pds-jira.jpl.nasa.gov/browse/CCB-325) for more details. Info to validate in this doc: [white_paper_v4.pdf](https://github.com/NASA-PDS/validate/files/10935999/white_paper_v4.pdf) (see `Testing for PDS MP4 Compliance` section)

### Acceptance Criteria

**Given** an properly labeled and valid MP4/H.264 encoded video product
**When I perform** validation of that data content
**Then I expect** validate to complete successfully

**Given** an properly labeled but invalid MP4/H.264 encoded video product
**When I perform** validation of that data content
**Then I expect** validate to fail with an ERROR

### ⚙️ Engineering Details

Related to https://github.com/NASA-PDS/pds4-information-model/issues/616

**Comment by thareUSGS** [comment]
Using this command using ffmpeg, I generated this H.264 video from Ingenuity helicopter sol 120:
`ffmpeg -r 30  -s 640x480 -i sol120_%04d.png -vcodec libx264 -crf 13 ingenuity_sol120_30fps_crf13.mp4`

Note I had to use "-crf 13" for the quality flag to fit the filesize under 10MB for github. Recommended is crf 12 or 10.

https://user-images.githubusercontent.com/3095138/235797141-1d67c6ae-69ef-41ea-834c-cc32eee90470.mp4

**Comment by jordanpadams** [comment]
@al-niessner see comment here for awaiting additional input:  https://github.com/NASA-PDS/validate/issues/605#issuecomment-1544715006 

here is what I think an example label would look like, but awaiting input on how to label products that are video+audio
[example.xml.txt](https://github.com/NASA-PDS/validate/files/11456515/example.xml.txt)
