### ISSUE TITLE
Support for Encoded Video and Encoded Audio

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#606]
## 💡 Description

- https://github.com/NASA-PDS/validate/issues/662
- https://github.com/NASA-PDS/validate/issues/663
- https://github.com/NASA-PDS/validate/issues/604
- https://github.com/NASA-PDS/validate/issues/605
- https://github.com/NASA-PDS/validate/issues/664

**Comment by jordanpadams** [comment]
@al-niessner this is probably the next big ticket item to complete. see sub-tasks for new requirements.

**Comment by al-niessner** [comment]
@jordanpadams 

Neither of these have example data. Can we get a product with both or two products that we think should work at least?

**Comment by jordanpadams** [comment]
@al-niessner 

[Uploading example.xml.txt…]()

Basically we just need to key off of if label includes `Encoded_Video` or `Encoded_Audio`, then we need to check the file matches to standards noted above. We then need to wrap the tools called out in the whitepaper to check the file matches the standard.

@thareUSGS any idea how we can introduce something to one of these files that would make it invalid?

**Comment by thareUSGS** [comment]
I can encode one using a vp9 video and opus audio encoding ([WebM](https://trac.ffmpeg.org/wiki/Encode/VP9)), both not allowed. Note: free audio file "[SCIShip_Spaceship passage 1 (ID 1971)_BSB.wav](https://bigsoundbank.com/sound-1971-spaceship-passage-1.html)" from https://bigsoundbank.com/

https://github.com/NASA-PDS/validate/assets/3095138/64a25dae-f03b-43cc-9c0c-c109417af241

`ffmpeg -i ingenuity_sol120_30fps_crf13_fakeAudioAAC.mp4 -c:v libvpx-vp9 -b:v 2M -c:a libopus ingenuity_sol120_30fps_WEBM_fakeAudioOpus_NotAllowedPDS4.mp4`

You will see "Video: vp9" and "Audio: opus" in ffprobe or other metadata tools. Those encoding methods are currently not allowed in PDS4. 

```
 > ffprobe ingenuity_sol120_30fps_WEBM_fakeAudioOpus_NotAllowedPDS4.mp4
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: ...
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\ingenuity_sol120_30fps_WEBM_fakeAudioOpus_NotAllowedPDS4.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.45.100
  Duration: 00:00:12.42, start: 0.000000, bitrate: 2288 kb/s
    Stream #0:0(und): Video: vp9 (Profile 1) (vp09 / 0x39307076), yuv444p(tv, progressive), 640x480, 2194 kb/s, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 91 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
```

still working on PDS4 labels for these videos.

**Comment by jordanpadams** [comment]
📆 May status: Work ahead of schedule. Awaiting release of B13.1 to test PR and merge.

**Comment by jordanpadams** [comment]
All sub-tasks completed.
