### ISSUE TITLE
Missing validation of valid_maximum and valid_minimum from Special_Constants

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS-Incubator/validate#611]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

data engineers

### 💪 Motivation

Does validate look at Special_Constants/valid_maximum and _minimum? It doesn't seem to, and I can imagine that would be difficult given those fields' type.

Validate passes the attached even though some values are above valid_maximum in both fields

[Archive.zip](https://github.com/NASA-PDS/validate/files/10960786/Archive.zip)

### 📖 Additional Details

Could this possibly be related to https://github.com/NASA-PDS/validate/issues/529 ?

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by al-niessner** [comment]
In #529 the max/min values are defined via:

```
      <Object_Statistics>
        <maximum>0.113922</maximum>
        <minimum>0.007821</minimum>
        <mean>0.064969</mean>
        <standard_deviation>0.011258</standard_deviation>
      </Object_Statistics>
```

while in this ticket is being defined:

```
          <Special_Constants>
            <valid_maximum>444444444</valid_maximum>
          </Special_Constants>
```

While they both set a max/min value they are done differently. Tracing it back now but probably not overly related.

--- more

As suspected, when validate tries to do the min/max check for a field, they are showing up as null. This may be a parser problem and not a validate problem. Continuing to track the root cause.

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

The problem starts here:

https://github.com/NASA-PDS/validate/blob/59a6edc2aac9f739aec699c363ae3545d34b866a/src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java#L311

The start of it that the value is passed as a string. Each of the special constants are checked for equality including max/min here:

https://github.com/NASA-PDS/validate/blob/59a6edc2aac9f739aec699c363ae3545d34b866a/src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java#L362-L371

The impulse is to use String.compareTo() to handle the greater-than/less-than for max/min respectively. Numbers as strings do not work well in this situation because "12" is less than "2" while 2 is obviously less than 12.

Where is the schema for `<Special_Constants>`. If the schema says it must be a number then the solution is simply to covert everything to BigDecimal or BigInteger then do a comparison. Otherwise it is going to get way messier with a more specialized comparator.

Do we have the PDS4 schema somewhere? I thought I had it, but it is not in my inbox -- I do not delete email except by accident. Cannot find it in jparser either.

**Comment by jordanpadams** [comment]
@al-niessner copy. thanks for tracking this down. here is the part of the IM: https://pds.nasa.gov/datastandards/documents/im/v1/index_1J00.html#10.42%C2%A0%C2%A0class_pds_special_constants

**Comment by jordanpadams** [comment]
@al-niessner looks like they are all Strings, but that seems like a bug to me? so we should probably convert for now, and then get the schema bug fixed. thoughts?

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

Strings are fine. It means that you can have a max/min values for strings as well. Say you want A-M and in another area N-Z this structure would cover it. It is just messy because the field validator converts the value string as the type demands then converts back to string for this bit. Now going to have to convert back to proper type again.

Agreed, just gonna have to go with a complex converter.

**Comment by jordanpadams** [comment]
@al-niessner thanks. had an email chain with @jshughes to discuss further.

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

Have a correct check for max now. It returns to field check that the value exceeds the max, but no error is generated. In fact, the field validation only notes an INFO when the value matches any of the special values. Are you sure you want special constants to throw the same error as a tables record max/min limits?

**Comment by jordanpadams** [comment]
@al-niessner this should definitely raise an ERROR. not sure which error is should raise, or if we need to create a new one, but one should show up in the report.

**Comment by miguelp1986** [comment]
@al-niessner @jordanpadams running Validate with the test files does not result in an `ERROR  [error.table.field_value_out_of_min_max_range]`

```
validate ~/repositories/validate/src/test/resources/github611/GRD-L1A-150313-150319_150625-BGO.xml                                                   ─╯

PDS Validate Tool Report

Configuration:
   Version                       3.2.0-SNAPSHOT
   Date                          2023-04-27T19:58:16Z

Parameters:
   Targets                       [file:/Users/MPena/repositories/validate/src/test/resources/github611/GRD-L1A-150313-150319_150625-BGO.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /usr/local/validate-3.2.0-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/Users/MPena/repositories/validate/src/test/resources/github611/GRD-L1A-150313-150319_150625-BGO.xml
        1 product validation(s) completed

Summary:

  0 error(s)
  0 warning(s)

  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped


End of Report
Completed execution in 3495 ms
```

**Comment by miguelp1986** [comment]
Retested with [v3.2.0](https://github.com/NASA-PDS/validate/tree/v3.2.0) and test now passes:
```
validate ~/repositories/validate/src/test/resources/github611/GRD-L1A-150313-150319_150625-BGO.xml                                             ─╯

PDS Validate Tool Report

Configuration:
   Version                       3.2.0
   Date                          2023-05-02T18:05:18Z

Parameters:
   Targets                       [file:/Users/MPena/repositories/validate/src/test/resources/github611/GRD-L1A-150313-150319_150625-BGO.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /usr/local/validate-3.2.0/resources/registered_context_products.json



Product Level Validation Results

  FAIL: file:/Users/MPena/repositories/validate/src/test/resources/github611/GRD-L1A-150313-150319_150625-BGO.xml
    Begin Content Validation: file:/Users/MPena/repositories/validate/src/test/resources/github611/GRD-L1A-150313-150319_150625-BGO.TAB
      ERROR  [error.table.field_value_out_of_min_max_range]   data object 1, record 1, field 2: Field has a value '479489128' that is greater than the defined maximum value '444444444'.
      ERROR  [error.table.field_value_out_of_min_max_range]   data object 1, record 1, field 94: Field has a value '3647' that is greater than the defined maximum value '2222'.
      ERROR  [error.table.field_value_out_of_min_max_range]   data object 1, record 1, field 95: Field has a value '3135' that is greater than the defined maximum value '2222'.
      ERROR  [error.table.field_value_out_of_min_max_range]   data object 1, record 1, field 98: Field has a value '2271' that is greater than the defined maximum value '2222'.
      ERROR  [error.table.field_value_out_of_min_max_range]   data object 1, record 1, field 99: Field has a value '2975' that is greater than the defined maximum value '2222'.
      ERROR  [error.table.field_value_out_of_min_max_range]   data object 1, record 2, field 2: Field has a value '479489338' that is greater than the defined maximum value '444444444'.
      ERROR  [error.table.field_value_out_of_min_max_range]   data object 1, record 2, field 94: Field has a value '2847' that is greater than the defined maximum value '2222'.
      ERROR  [error.table.field_value_out_of_min_max_range]   data object 1, record 2, field 95: Field has a value '3039' that is greater than the defined maximum value '2222'.
      ERROR  [error.table.field_value_out_of_min_max_range]   data object 1, record 2, field 99: Field has a value '2463' that is greater than the defined maximum value '2222'.
    End Content Validation: file:/Users/MPena/repositories/validate/src/test/resources/github611/GRD-L1A-150313-150319_150625-BGO.TAB
        1 product validation(s) completed

Summary:

  9 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    9            error.table.field_value_out_of_min_max_range

End of Report
Completed execution in 6192 ms
```

**Comment by rchenatjpl** [comment]
@al-niessner @jordanpadams Ignore this? Disallow this? Allow this but impose a syntax for hex values? The attached label is migrated from PDS3. Near the bottom is:
```
        <data_type>IEEE754LSBSingle</data_type>
      ...
      <Special_Constants>
        <missing_constant>16#FF7FFFFB#</missing_constant>
        <high_instrument_saturation>16#FF7FFFFE#</high_instrument_saturation>
        <high_representation_saturation>16#FF7FFFFF#</high_representation_saturation>
        <valid_minimum>-32752</valid_minimum>
        <low_instrument_saturation>16#FF7FFFFD#</low_instrument_saturation>
        <low_representation_saturation>16#FF7FFFFC#</low_representation_saturation>
      </Special_Constants>
```
which says that if the float has 4 hex bytes of FF7FFFFx (x=B|C|D|E|F), it's one of those situations. However, validate doesn't recognize the hits and treats the pixels as floats (huge negatives) and throws an error for each occurrence, which is in the thousands.
(I butchered the .IMG to get under github's max attachment size. I think I fixed the .xml and .IMG well enough)
[hexConstants.zip](https://github.com/NASA-PDS/validate/files/11521508/hexConstants.zip)

**Comment by al-niessner** [comment]
@rchenatjpl @jordanpadams 

While I appreciate that this seems related to #611 via the special constants, it is really about magic processing of floats represented as hex and should be opened as a new issue if we choose to move forward with it.

Please clarify: The previous comment states "which says that if the float has 4 hex bytes of FF7FFFFx (x=B|C|D|E|F), it's one of those situations." but it does not give the "then" part of the "if" of the statement. In other words, okay the values end in "D" and "C" which meets the condition of the if, but it does not have the "then" indicating what to do when the condition is met. Maybe what to do is well know to you two but it is unknown to me.

**Comment by rchenatjpl** [comment]
I'm not sure what validate should do with them. IMO those constructs are for data processors so that they can skip over that data. I think (anyone, feel free to overrule) that validate should 1) definitely not flag them as being too high or too low, and 2) does validate have levels of warnings or infos? If so, mark them at a really low level, with a message like "305838 unknown_constants found, initially at x,y"

And you're going to do the hex checking? Awesome. Can you also allow the syntax 0xff6ffffx - I don't know why PDS3 used 16#whatever#, though that does allow you to write 2#somebinarystring# and 8#octaltoo#. OK, I guess those are good reasons, but 0x is so standart IMO.

**Comment by al-niessner** [comment]
non sequitur:
0b1001010 - binary
0o1234 - octal
0xabcd - hex

2#, 8#, and 16# might be clearer but the others are pretty common.

**Comment by al-niessner** [comment]
I think it is an error because if the saturation is 3 and the value is 4 then some error exists because 4 cannot be generated because it is past saturation except by error.

**Comment by rchenatjpl** [comment]
The Special_Constants are artificial values inserted when the instrument encounters anomalous situations. That includes the saturation constants, which are not limits beyond which the instrument is even more saturated. 

II can't remember ever seeing 0b or 0o, but if you allow those, that's great. I'd definitely want to allow 0X regardless of whether you allow 0O.

**Comment by msbentley** [comment]
Sorry for butting in here, but is this `<missing_constant>16#FF7FFFFB#</missing_constant>` kind of notation "a thing" in PDS4? I don't recall reading about it. On the other hand I would suuuuuuper happy if there were a way to specify Special_Constants based on their underlying bit pattern, since comparing two float values is dicy...

**Comment by rchenatjpl** [comment]
Not at all, Mark. I do have a preference for what notation we should use (0x and 0X and maybe the others mentioned above), but we should probably support the PDS3 syntax based on our sample size of 1, though it might be acceptable to force them to use whatever notation we come up with, though that would probably entail much discussion with all parties.

**Comment by rchenatjpl** [comment]
Another vote for 0x, this from the producers of the migrated PDS3 labels that started this: 

Date: Wed, 24 May 2023 16:47:47 -0700

**Comment by rchenatjpl** [comment]
@jordanpadams @al-niessner Can we raise the priority of allowing hex specifications, including for valid_minimum and _maximum? The LROC data is due to be migrated soon, and the data files actually use the constants given above, and the valid_minimum warning/error keeps getting thrown.

**Comment by jordanpadams** [comment]
@rchenatjpl yes we will look into this next.

**Comment by jordanpadams** [comment]
@rchenatjpl we are checking in with DDWG as well just to get extra clarification added to the standard

**Comment by jordanpadams** [comment]
closing this ticket since I think this is a separate requirement altogether for supporting bit patterns in Special_Constants

**Comment by radiosci** [comment]
There may be some misunderstandings about how Special_Constants should be used.  
(1) valid_maximum and valid_minimum only identify those values as the bounds on the valid range.  Values outside the valid range "have special meanings" (see the definitions of these attributes); if those values are encountered, they should not be flagged as errors.  The user should recognize them and respond appropriately.
(2) since all attributes under Special_Constants are ASCII_Short_String_Collapsed, it is very difficult to use them in any context that is not ASCII.  For example, there will usually be mismatches when comparing values in binary tables with Special_Constants because of round-off errors.  And there is no guarantee that a Special_Constant in hexadecimal will match its target unless the target is also an ASCII representation of a hex value.  The same is true for bit strings.
If we want to use Special_Constants with anything other than ASCII products, we will need a complete overhaul of the Special_Constants specification.

**Comment by al-niessner** [comment]
@radiosci @jordanpadams 

Yes, we are in agreement on point (1). If they are special values they should not be flagged as errors for being out of range.

If a bit pattern is specified in ASCII as either `16#a#` or `0xa`, then it can be checked without rounding error even in binary tables - your second point. When doing the comparison, the ASCII string would be converted to the exact bit pattern (think integer) and the binary form would be read as bits (again think integer). Both would then be the same number of bits and not floats that can then be compared bitwise (again think integer). Hope that clarifies the misconception that the types would have to be compared as the type given.

**Comment by radiosci** [comment]
If Special_Constants are specified as the observed value, rather than the stored value, then I think we agree on (2).  It won't matter whether float or integer values are stored as MSB or LSB so long as the bit patterns match when the observed values are compared.  The same principle can be applied to bit strings.

**Comment by jordanpadams** [comment]
@rchenatjpl per the closeout of https://github.com/NASA-PDS/validate/issues/651, once [that build has completed](https://github.com/NASA-PDS/validate/actions/runs/5425194543), you should be able to test this out with the latest SNAPSHOT of validate.

**Comment by kbowley-asu** [comment]
I grabbed a copy of the latest snapshot and it's throwing an error when validating the same file that @al-niessner was using.  This is on an Ubuntu 20.04 system:
```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:64)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
        at gov.nasa.pds.tools.validate.task.ValidationTask.execute(ValidationTask.java:130)
        at gov.nasa.pds.tools.validate.task.BlockingTaskManager.submit(BlockingTaskManager.java:26)
        at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:285)
        at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1445)
        at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1731)
        at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1780)
Caused by: java.lang.NoSuchMethodError: java.lang.String.strip()Ljava/lang/String;
        at gov.nasa.pds.tools.label.LabelValidator.checkSchemaSchematronVersions(LabelValidator.java:384)
        at gov.nasa.pds.tools.label.LabelValidator.parseAndValidate(LabelValidator.java:480)
        at gov.nasa.pds.tools.validate.rule.pds4.LabelValidationRule.validateLabel(LabelValidationRule.java:316)
        ... 12 more

PDS Validate Tool Report

Configuration:
   Version                       3.3.0-SNAPSHOT
   Date                          2023-06-30T17:20:53Z

Parameters:
   Targets                       [file:/scratch0/kbowley/edr_cdr_pds4_test/M1431146123CC.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /scratch0/kbowley/pds4/validate-3.3.0-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  FAIL: file:/scratch0/kbowley/edr_cdr_pds4_test/M1431146123CC.xml
      ERROR  [error.validation.internal_error]   Error executing validationTask: java.lang.NoSuchMethodError: java.lang.String.strip()Ljava/lang/String;
        1 product validation(s) completed

Summary:

  1 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.validation.internal_error

End of Report
Completed execution in 4640 ms

```

**Comment by jordanpadams** [comment]
@kbowley-asu what version of Java are you running?

```
java -version
```

It looks like our [documentation](https://nasa-pds.github.io/validate/install/index.html#System_Requirements) calls out that Validate requires Java version 9+, but it looks like it now requires Java 11+ (openjdk). Sorry for the inconvenience.

**Comment by kbowley-asu** [comment]
That was the error.  Due to some legacy tools, my default java was set to 8.  I set the JAVA_HOME to point to 11 and everything worked as expected.  Thanks for pointing me in the right direction!
