### ISSUE TITLE
As a data engineer, I want to run the validator multi-threaded.  Is that a possibility now or in the future?

### ISSUE THREAD

**Issue by bharris-igpp** [NASA-PDS-Incubator/validate#612]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

impatient data engineers

### 💪 Motivation

spend less time waiting

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
@bharris-igpp under [Advanced Bundle Validation documentation](https://nasa-pds.github.io/validate/operate/index.html#Advanced_Bundle_Validation), there is a subsection **Using validate-bundle parallelization** that discusses another command-line tool that comes with validate that will parallelize a bundle. There are also some other tips for how to manually parallelize execution on multiple directories.
