### ISSUE TITLE
As a user, I would like to enforce browse file extension with encoding type

### ISSUE THREAD

**Issue by mace-space** [NASA-PDS-Incubator/validate#617]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data users

### 💪 Motivation

so that the <encoding_standard_id> matches the file type in the <File_Area_Browse> 

### 📖 Additional Details

A browse label containing the following passed validation with no errors or warnings:

```
 <File_Area_Browse>
        <File>
            <file_name>uvis_euv_2005_159_solar_time_series_ingress.jpg</file_name>
            <creation_date_time>2023-03-08T14:22:14</creation_date_time>
        </File>
        <Encoded_Image>
            <offset unit="byte">0</offset>
            <encoding_standard_id>PNG</encoding_standard_id>
        </Encoded_Image>
    </File_Area_Browse>
```

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect** 

### ⚙️ Engineering Details

Per IM Spec, it looks like we should check the file extensions for the following file types.

Possible values for `//Encoded_Image/encoding_standard_id`:
- GIF - The Encoded_Image is governed by the standard Graphics Interchange Format (GIF).
- J2C - The Encoded_Image is governed by the standard JPEG2000 compressed image codestream.
- JPEG - The Encoded_Image is governed by the standard Joint Photographic Experts Group (JPEG), ISO/IEC 10918-1.
- PDF - The Encoded_Image is governed by the standard Portable Document Format (PDF), ISO 32000-1:2008.
- PDF/A - The Encoded_Image is governed by the standard Portable Document Format / Archive (PDF/A), ISO 19005-1:2005.
- PNG - The Encoded_Image is governed by the standard Portable Network Graphics (PNG), ISO/IEC 15948:2004.
- TIFF - The Encoded_Image is governed by the standard Tagged Image File Format (TIFF), Version 6.n, 1992.

**Comment by mace-space** [comment]
I wasn't able to assign any labels, such as "enhancement" or "low priority", but I imagine those get assigned during triage?

**Comment by jordanpadams** [comment]
@mace-space sorry for the delay. looks like my initial comment never went through.

would this be OK as a WARNING? we can't really throw an ERROR here because the standard doesn't really say anything about what file extensions are associated with each encoding type. we can guess and throw a warning, but that is it.

**Comment by mace-space** [comment]
Thanks, @jordanpadams. Throwing a warning would be very useful.

**Comment by al-niessner** [comment]
@jordanpadams 

What is you want to test:
1. the file suffix/extension does not match the tag as in '.jpg' does not match 'PNG'? Who determines the suffix that JPEG can have as jpg and jpeg are both common and there are more with case sensitivity. Then there are the MIME definitions for JPEG: .jpg , .jpeg , .jpe , .jif , .jfif
3. the file suffix/extension does not match the file content as in '.jpg' does not match the TIFF content in the file? Should the file be read as JPEG and if it fails declare them a mismatch?
4. the label and file content?
5. 1 through 3? If this case, then are they different warnings or all three test generate a single warning.

**Comment by jordanpadams** [comment]
@al-niessner 

> 1. the file suffix/extension does not match the tag as in '.jpg' does not match 'PNG'? Who determines the suffix that JPEG can have as jpg and jpeg are both common and there are more with case sensitivity. Then there are the MIME definitions for JPEG: .jpg , .jpeg , .jpe , .jif , .jfif

we just want to check that the encoding standard id in the label, matches one of the expected "common" file extensions for that encoding standard. the encoding standards we need to worry about are:

- GIF - The Encoded_Image is governed by the standard Graphics Interchange Format (GIF).
- J2C - The Encoded_Image is governed by the standard JPEG2000 compressed image codestream.
- JPEG - The Encoded_Image is governed by the standard Joint Photographic Experts Group (JPEG), ISO/IEC 10918-1.
- PDF - The Encoded_Image is governed by the standard Portable Document Format (PDF), ISO 32000-1:2008.
- PDF/A - The Encoded_Image is governed by the standard Portable Document Format / Archive (PDF/A), ISO 19005-1:2005.
- PNG - The Encoded_Image is governed by the standard Portable Network Graphics (PNG), ISO/IEC 15948:2004.
- TIFF - The Encoded_Image is governed by the standard Tagged Image File Format (TIFF), Version 6.n, 1992.

not sure if there is some standard we can follow for what those file extensions should be? this is probably something we should manage with some config file so it is easily updatable?

**Comment by al-niessner** [comment]
@jordanpadams 

Will use MIME for initial set of allowed extensions.

Since we have to change config or code then repackage, why config over code as long as they are both simple to extend?

**Comment by jordanpadams** [comment]
@al-niessner that is fine. whatever you think is best

**Comment by al-niessner** [comment]
@jordanpadams 

Can we get a complete example rather than just XML stub?

**Comment by mace-space** [comment]
@al-niessner please find a complete example browse label attached
[uvis_euv_2005_159_solar_time_series_ingress.txt](https://github.com/NASA-PDS/validate/files/11352165/uvis_euv_2005_159_solar_time_series_ingress.txt)
Thanks
