### ISSUE TITLE
Expected value in validate report for context reference name is not same as value in the context file

### ISSUE THREAD

**Issue by murashinln** [NASA-PDS-Incubator/validate#631]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When I did use validate command with `-v 1` option to the Hayabusa2 TIR data product, I noticed some Context reference name case mismatch `[info.label.context_ref_case_mismatch]` information lines like following:
```
 PASS: file:/nasA_planetc/vco_work/pds4/repos/vco/validate/bin/hyb2_tir_20180629_075501_l1.xml
      INFO  [info.label.filesize_matches]   Generated filesize '400320' matches the supplied filesize '400320' in the product label for 'file:/nasA_planetc/vco_work/pds4/repos/vco/validate/bin/hyb2_tir_20180629_075501_l1.fit'
      INFO  [info.label.context_ref_found]   line 41: Context product found: 'urn:jaxa:darts:context:investigation:mission.hyb2'
      INFO  [info.label.context_ref_mismatch]   line 41: Context reference name mismatch. Value: 'Hayabusa2' Expected one of: '[HAYABUSA2 ASTEROID SAMPLE RETURN MISSION]'
      INFO  [info.label.context_ref_found]   line 50: Context product found: 'urn:jaxa:darts:context:instrument_host:spacecraft.hyb2'
      INFO  [info.label.context_ref_found]   line 58: Context product found: 'urn:jaxa:darts:context:instrument:hyb2.tir'
      INFO  [info.label.context_ref_mismatch]   line 58: Context reference name mismatch. Value: 'TIR' Expected one of: '[THERMAL INFRARED IMAGER (TIR)]'
      INFO  [info.label.context_ref_found]   line 67: Context product found: 'urn:nasa:pds:context:target:asteroid.162173_ryugu'
      INFO  [info.label.context_ref_case_mismatch]   line 67: Context reference name case mismatch. Value: '(162173) Ryugu' Expected one of: '[(162173) RYUGU]'
      INFO  [info.label.context_ref_case_mismatch]   line 67: Context reference type case mismatch. Value: 'Asteroid' Expected one of: '[ASTEROID]'
      INFO  [info.label.local_identifier_found]   line 97: Referenced Local Identifier 'ImageData' found in label on line '195'.
      INFO  [info.label.local_identifier_found]   line 109: Referenced Local Identifier 'ImageData' found in label on line '195'.
        1 product validation(s) completed
```

In the [asteroid.162173_ryugu_1.0.xml](https://pds.nasa.gov/data/pds4/context-pds4/target/asteroid.162173_ryugu_1.0.xml), `Product_Context/Target/name` is `(162173) Ryugu`, and the expected value indicated in the validate command report is `(162173) RYUGU`. It should be `(162173) Ryugu` and `[info.label.context_ref_case_mismatch]` should not be reported because the value of `Product_Observational/Observation_Area/Target_Identification/name` in the XML label is same as the value of `Product_Context/Target/name` in the context product including the case of string.

### 🕵️ Expected behavior

I expected info.label.context_ref_case_mismatch is not reported if I used same string for context reference name in XML label including the case of string with the value in the context products.

### 📜 To Reproduce

1. get [hyb2_tir_20180629_075501_l1.xml](https://sbnarchive.psi.edu/pds4/hayabusa2/hyb2_tir/data_raw/proximity/20180629/hyb2_tir_20180629_075501_l1.xml) and [hyb2_tir_20180629_075501_l1.fit](https://sbnarchive.psi.edu/pds4/hayabusa2/hyb2_tir/data_raw/proximity/20180629/hyb2_tir_20180629_075501_l1.fit) .
2.  do `validate -v 1 -t hyb2_tir_20180629_075501_l1.xml`

### 🖥 Environment Info

- Operating System: Red Hat Enterprise Linux Server release 7.9

### 📚 Version of Software Used

- Version of this software: validate 3.2.0

### ⚙️ Engineering Details

- [ ] update context name check to be case agnostic
- [ ] verify checks are successful with the values noted above

**Comment by jordanpadams** [comment]
@rchenatjpl can we update the Ryugu context product? It should just be a case update.

**Comment by rchenatjpl** [comment]
I don't know, @jordanpadams - Both the context product and murashinin's .xml file have
```
            <name>(162173) Ryugu</name>
            <type>Asteroid</type>
```
 Is there a reason they should be all uppercase?

**Comment by murashinln** [comment]
I forgot to write that same thing happens to Venus, Ultraviolet Imager, etc. during validation of Akatsuki's labels which is under preparation. I guessed validate command use `resources/registered_context_products.json` and it seems that so many names are registered in uppercase there.

**Comment by al-niessner** [comment]
@jordanpadams 

How do you want to fix this? The registered_context_products.json is the only change but I am sure that it will break some and fix others. Mainly there are many case checking issues and they all relate back to the same JSON file:

```
      INFO  [info.label.context_ref_mismatch]   line 41: Context reference name mismatch. Value: 'Hayabusa2' Expected one of: '[HAYABUSA2 ASTEROID SAMPLE RETURN MISSION]'
      INFO  [info.label.context_ref_mismatch]   line 58: Context reference name mismatch. Value: 'TIR' Expected one of: '[THERMAL INFRARED IMAGER (TIR)]'
      INFO  [info.label.context_ref_case_mismatch]   line 67: Context reference name case mismatch. Value: '(162173) Ryugu' Expected one of: '[(162173) RYUGU]'
      INFO  [info.label.context_ref_case_mismatch]   line 67: Context reference type case mismatch. Value: 'Asteroid' Expected one of: '[ASTEROID]'
```

Arguably in for TIR and Hayabusa2 it is way more than case. Who dictate the contents of the JSON file?

**Comment by jordanpadams** [comment]
@al-niessner the JSON is auto-generated in ValidateLauncher using the `-u` flag.

> Arguably in for TIR and Hayabusa2 it is way more than case

Correct. those are valid failures, so nothing needs to be done there.

for the others, I just want us to (1) verify the issue is with upper vs lower case and nothing else, and (2) if so, make the check case agnostic
