### ISSUE TITLE
Document how to use validate-refs tool in Validate Operation User Guide

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#643]
## 💡 Description

Create new `Validating References` section in [Operation User Guide](https://github.com/NASA-PDS/validate/blob/main/src/site/xdoc/operate/index.xml.vm) for basic configuration and usage of validate-refs utility.

**Comment by al-niessner** [comment]
@jordanpadams 

Starting this term paper and looking for excuses to not do it. The user guide linked in the problem description clearly states:
https://github.com/NASA-PDS/validate/blob/ed9c1dea9b315af0f770165b6cf62430f5a861ea/src/site/xdoc/operate/index.xml.vm#L42

Should I add the integrity check as a section of validation with its own table of contents (TOC) as subsections if needed or just make it a standalone TOC section then more sections if and as needed?

**Comment by jordanpadams** [comment]
@al-niessner +1 on the new TOC section and add that information.
