### ISSUE TITLE
Validate gives errors for 'NaN' and 'Inf' values in IEEE754 data

### ISSUE THREAD

**Issue by mnhughes** [NASA-PDS-Incubator/validate#644]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When validating M2020 SuperCam FITS data files, validate v. 3.2.0 gives an error for 'NaN' and 'Inf" values in the data. 
[SuperCamFITSvalidate.zip](https://github.com/NASA-PDS/validate/files/11465946/SuperCamFITSvalidate.zip)

Why does validate say that these values aren't allowed in IEEE754MSBDouble data? I can't find anything saying this in the PDS4 standards. I only see these values aren't allowed in ASCII data. 

Validate 3.2.0 is also still giving the offset error for tables defined out of order which I thought was fixed in 3.2.0.

### 🕵️ Expected behavior

I expected this product to pass validation.

### 📜 To Reproduce

1.
2.
3.
...

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 📚 Version of Software Used

3.2.0

### 🦄 Related requirements

🦄 #532
🦄 #514

**Comment by al-niessner** [comment]
@jordanpadams @mnhughes 

I am getting this error in the sample data and do not understand it well enough to fix it. It also seems unrelated to this ticket:
```
  FAIL: file:/home/niessner/Projects/PDS/validate/src/test/resources/github644/scam_0072_0673327336_185_cp2_scam01072_scct_41_irsalign_____04p04.xml
      ERROR  [error.label.invalid_object_definition]   line 12: Invalid object definition for object #12.  The previously defined object ends at byte 146432. Offset defined in label: 141120
        1 product validation(s) completed
```

May have missed it in the flood of NAN errors but those have been removed. Please help me fix this error in the XML for FITS to close this ticket.

**Comment by jordanpadams** [comment]
@al-niessner @mnhughes it looks like the `IR HK TABLE` starts at byte 138240, and has an object length of 8192 bytes (256 records x 32 byte record length), so the `SPECTRA HEADER` object should have an offset of 146432. the remaining offsets are probably after that as well

**Comment by mnhughes** [comment]
I talked with the data provider and there was an error in their label templates which likely caused that issue (as well as the values in some of the tables that were very off).
