### ISSUE TITLE
As a user, I want the PDF error reports to be output in a user-specified directory

### ISSUE THREAD

**Issue by tbarnes4** [NASA-PDS-Incubator/validate#658]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Anyone using validate when they have an invalid pdf file and want to save the validate error report to file in a different location from the pwd.

### 💪 Motivation

Low priority.  If I am running validate in a location that cannot or should not have files created, and/or if I simply want the *.pdf.1b.error.csv error report file to be stored side by side with the saved validate error report (when using the -r option), it would be nice if validate can do this automatically.  Currently if there is an error with the PDF file, the *.pdf.1b.error.csv report will be outputted to the present working directory, even if the -r option is declared.  I think great if the -r option is declared that the *.pdf.1b.error.csv report will be stored in the same directory that the -r option points to.  If the -r creates a file in the pwd, than the *.pdf.1b.error.csv report will also there.

### 📖 Additional Details

Example case.  Run validate on the [urn:nasa:pds:compil-comet:halebopp::1.0](https://pdssbn.astro.umd.edu/holdings/pds4-compil-comet:halebopp-v1.0/SUPPORT/dataset.shtml) collection.

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by al-niessner** [comment]
@jordanpadams @tbarnes4 

It seems `-r` is to a report file not a directory. In other words, many users might be surprised, disappointed, irritated, etc - I know i would be - if I started getting dodo files in a directory where I only wanted validate reports so they could be grepped, processed, and archived. I would also be surprised, disappointed, irritated etc if dodo files showed up in my current directory as well.

I would suggest that we add a new flag for dodo files that users may want. The main question would be do we want to keep the default behavior of creating dodo files in the current directory or not at all if the new flag is not used. Could put a warning in the report that validate wanted to create further reports but new flag was not given so reports were trashed. I recommend the latter.

**Comment by tbarnes4** [comment]
@al-neissner @jordanpadams 

My two cents as a user.

I agree.  I was not thinking of how it might be annoying to put the 'dodo files' in the same location as the outputted report file without notifying the user.  I agree that adding a new flag would probably be best.  You will just want to specify in the error report where the 'dodo' file is placed since the error message asks the user to look at it.  

Unless it is made clear that validate *might* create additional errors files in XYZ location, I would not allow it by default.  I think a warning would be appropriate and then directing the user to run validate on the individual file with the new flag to see the additional errors.   It surprised me when oddly named files were appearing in my working directory.  My first thought was that something was not working as expected, until I found their reference in the error report and then I was glad I knew where they were since the error report appeared to assume they were a default location, not where I put my reports.

**Comment by jordanpadams** [comment]
@tbarnes4 once https://github.com/NASA-PDS/validate/actions/runs/5383306369 completes, you should be able to [grab the latest SNAPSHOT](https://github.com/NASA-PDS/validate/releases) to test out the new `--pdf-errors` flag to specify a directory to output the PDF error reports.

**Comment by tbarnes4** [comment]
@jordanpadams Thanks!  I'll take a look when it is ready.
