### ISSUE TITLE
Implement content validation for audio/video formats

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#664]
## Related Requirements
* 🦄 https://github.com/NASA-PDS/validate/issues/663
* 🦄 https://github.com/NASA-PDS/validate/issues/662
* 🦄 https://github.com/NASA-PDS/validate/issues/605
* 🦄 https://github.com/NASA-PDS/validate/issues/604

**Comment by al-niessner** [comment]
1. Here is an MP4 library but it does not decode:  
    https://github.com/sannies/mp4parser

1. Here is another but it wraps FFMPEG library:  
    https://www.xuggle.com/xuggler/

1. IBM Alphaworks is gone.

1. Apache Tika but that seems to be more of version of validate than verifying mp4 but it also cannot decode:  
    https://tika.apache.org/

**Comment by al-niessner** [comment]
1. Here is an H264 decoding library but it depends on FFMPEG:  
    https://www.xuggle.com/xuggler/

1. Here is another H264 decoding library but is not yet available despite google claiming it is ready:  
    http://jcodec.org/  
    https://github.com/jcodec/jcodec seems to be alive and valid

1. Java Media Framework support MP3 not 4.

**Comment by al-niessner** [comment]
1. AAC decoder seems to be available through:  
    https://github.com/DV8FromTheWorld/JAADec

**Comment by al-niessner** [comment]
@jordanpadams 

What does it mean to verify the content of an MP4? Just that the metadata that says it is H264 and/or AAC or do we have to verify the bit streams through a decoder? See above comments. It seems will depend on some other maven modules but being they are maven should make it OK - maybe. Moving forward with having to decode just to see how slow (or maybe fast) it would be.

**Comment by jordanpadams** [comment]
@thareusgs thoughts? ☝️

**Comment by thareUSGS** [comment]
> Just that the metadata that says it is H264 and/or AAC or do we have to verify the bit streams through a decoder?

For video and audio, I am very much in the camp of simply making sure "the metadata that says it is H264 and/or AAC".  For other checks, outside of a simple chksum, I could see using ffmpeg to test the file (but I know having to yet add another 3rd party code/binary can be a burden). For example, we could run this and then parse the output for an error:
`ffmpeg -v error -i file.mp4 -f null - 2>error.log`
    as shown here: https://superuser.com/questions/100288/how-can-i-check-the-integrity-of-a-video-file-avi-mpeg-mp4/1241089#1241089

**Comment by al-niessner** [comment]
@jordanpadams @thareUSGS 

> > Just that the metadata that says it is H264 and/or AAC or do we have to verify the bit streams through a decoder?
> 
> For video and audio, I am very much in the camp of simply making sure "the metadata that says it is H264 and/or AAC". For other checks, outside of a simple chksum, I could see using ffmpeg to test the file (but I know having to yet add another 3rd party code/binary can be a burden). For example, we could run this and then parse the output for an error: `ffmpeg -v error -i file.mp4 -f null - 2>error.log` as shown here: https://superuser.com/questions/100288/how-can-i-check-the-integrity-of-a-video-file-avi-mpeg-mp4/1241089#1241089

Biggest problem with FFMPEG is support on various platforms. I use linux but the command line may be different on other platforms and developing/testing other platforms is hard because I only have linux available. There are pure Java libraries quoted above but they may be slow.
