### ISSUE TITLE
validate does not handle special constants with data type of SignedLSB2

### ISSUE THREAD

**Issue by kbowley-asu** [NASA-PDS-Incubator/validate#674]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When I ran validate (3.3.0-SNAPSHOT) against a pds4 label with special constants for a product with a SignedLSB2 data type, I noticed that validate blew up with a FATAL_ERROR

### 🕵️ Expected behavior

I expected validate to validate the pds4 product without blowing up with a java error.

### 📜 To Reproduce

1. Download product and label from https://pds.lroc.asu.edu/data/LRO-L-LROC-3-CDR-V1.0/LROLRC_1055A/DATA/ESM5/2023075/NAC/M1433566422LC.IMG and https://pds.lroc.asu.edu/data/LRO-L-LROC-3-CDR-V1.0/LROLRC_1055A/DATA/ESM5/2023075/NAC/M1433566422LC.xml
2. run validate against the xml file
3. FATAL_ERROR  [error.array.bad_file_read]   array 1: Error occurred while reading data file: class java.lang.Short cannot be cast to class java.math.BigInteger (java.lang.Short and java.math.BigInteger are in module java.base of loader 'bootstrap')

### 🖥 Environment Info

- Version of this software 3.3.0-SNAPSHOT
- Operating System: Ubuntu Linux 20.04 with java 17

### 📚 Version of Software Used

$ validate --version

gov.nasa.pds:validate
Version 3.3.0-SNAPSHOT
Release Date: 2023-07-25 03:27:16

**Comment by jordanpadams** [comment]
@kbowley-asu I can replicate the issue. We will add this to the backlog. What is the urgency on this fix?

**Comment by kbowley-asu** [comment]
Due to the various updates to validating Special_Constants, version 3.1.1 is the last version of validate that we've been able to use.  I just noticed this bug when I tried using the latest SNAPSHOT version while working on some tweaks to our tools that generate PDS4 labels for our products.
