### ISSUE TITLE
Upgrade verapdf dependency per transitive log4j vulnerability

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#693]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

`mvn dependency:tree` I see log4j 1.2.17.

### 🕵️ Expected behavior

I expected no log4j 1.x

### 🦄 Related requirements

🦄 #164

**Comment by tloubrieu-jpl** [comment]
Pull request is approved, waiting to be merged.
