### ISSUE TITLE
Update inefficient regexes to potentially improve performance

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#708]
## 💡 Description

These code scanning notes identified ways we could potentially improve the performance of our regex. This is a definite nice-to-have (or wont-have).

As they say, if it ain't broke don't fix it.

- https://github.com/NASA-PDS/validate/security/code-scanning/13
- https://github.com/NASA-PDS/validate/security/code-scanning/12

**Comment by al-niessner** [comment]
@jordanpadams marking this as closed because they are cut-n-paste from PDS schema/schematron/documentation that prohibits changes. Also, have been using for quite a while and time to process is 1000x slower than any time from these regexps. Feel free to reopen for any reason.
