### ISSUE TITLE
Installation instructions need updates for Windows

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#723]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

Per user, numerous issues identified by user for windows installation.

### 🕵️ Expected behavior

I expected installation instructions would be valid

### 📜 To Reproduce

**PATH**
In https://nasa-pds.github.io/validate/install/index.html#windows-environment, the command to append Path is given as:   
```
C:\> set PATH = %PATH%;C:\Program Files\validate-3.2.0\bin
```
but would be best given as:
```
C:\> set Path=%Path%;C:\Program Files\validate-3.2.0\bin
```
The variable name is case-sensitive and must be specified as Path, there should be no space between the variable name and =, and all spaces after = are treated as part of the value. Strictly, the (case-insensitive) interpolation could use %PATH%, but %Path% seems clearer.

**JAVA_HOME**
In https://nasa-pds.github.io/validate/install/index.html#windows-environment, the command to set JAVA_HOME is given as:
```
C:\> set JAVA_HOME = C:\path\to\java\home
```
but should be:
```
C:\> set JAVA_HOME=C:\path\to\java\home
```
Also, someone passingly acquainted with Windows commands might expect that double-quotes are required for paths with spaces (as they are for some commands), but that is not the case here. To clue the user to this, it might be helpful to choose an example path with spaces, such as:
```
C:\> set JAVA_HOME=C:\path to java\home
```
or an example related to the default Java directory:
```
C:\> set JAVA_HOME=C:\Program Files\Java\some-jre-version
```

**Windows 64-bit JRE:**
The current instructions explicitly direct the user to install 64-bit JRE, which is helpful. However, I note that the 32-bit JRE is the default on Windows. Indeed, the online installer for Windows on the All Operating Systems page (https://www.java.com/en/download/manual.jsp) only installs the 32-bit JRE, even though this is not explicitly stated on the download page. Worse yet, the only JRE on the Windows-only download page (https://www.java.com/download/ie_manual.jsp) is 32-bit (though this is not stated), and that page is the first hit on a Google search for "java download" (at least, from my system). Therefore, it might help to highlight the 64-bit caveat in the installation instructions and include a reference to https://nasa-pds.github.io/validate/operate/errors.html#Invalid_maximum_heap_size under https://nasa-pds.github.io/validate/install/index.html#Verifying_the_Installation.

### 🖥 Environment Info

Windows OS

### I&T
TestRail Test ID: T8681189

**Comment by miguelp1986** [comment]
@jordanpadams should this be i&t.skip?

**Comment by jordanpadams** [comment]
@miguelp1986 I don't think so since we definitely want to make sure the installation instructions are valid for Windows, but this is probably validated by executing any of our smoke tests on Windows.

**Comment by miguelp1986** [comment]
@jordanpadams Looks like changes from https://github.com/NASA-PDS/validate/pull/725 were reverted somehow.
<img width="1208" alt="Screenshot 2024-05-02 at 12 12 17 AM" src="https://github.com/NASA-PDS/validate/assets/15747611/9b30cf00-4de1-4edc-b60d-c54e9fe55971">

<img width="1204" alt="Screenshot 2024-05-02 at 12 14 37 AM" src="https://github.com/NASA-PDS/validate/assets/15747611/3e22f937-1db4-49d2-9ce3-a069552140a7">

**Comment by nutjob4life** [comment]
@miguelp1986 thanks for noticing this; yes, it looks like the documentation got reverted in pull request #734 … and the lengthy copyright notices got added back too 😅

**Comment by jordanpadams** [comment]
@miguelp1986 ☝️ this should be fixed. it is not deployed yet online, but you should see it with `mvn site`
