### ISSUE TITLE
As a user, I want validate's referential integrity tool to read a manifest of files and check referential integrity

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#741]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Node Operator

### 💪 Motivation

...so that I can input a manifest of file paths, and `validate-refs` will parse all the labels and complete referential integrity for each of the products using the registry

### Acceptance Criteria

**Given** a target manifest of file paths to PDS4 labels
**When I perform** `validate-refs --target-manifest <manifest-file-name>`
**Then I expect** the software will check all lid and lidvid references from each label.

### ⚙️ Engineering Details
blocker for https://github.com/NASA-PDS/nucleus/issues/75

### I&T
TestRail Test ID: T8681200

**Comment by al-niessner** [comment]
@jordanpadams 

Is this not accomplished with 

`validate-refs $(cat manifest_file)`

or

`validate-refs < manifest_file`


Otherwise we have to define what a manifest looks like and then verify that they gave us one or more.
