### ISSUE TITLE
validate flags IEEE 754 "infinity" values as invalid

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS-Incubator/validate#747]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

We have some data in PSA using IEEE754LSBSingle and using infinity values. If I understand correctly, inf and nan should be allowed by the standards, and recent changes were made to validate to support this right? In validate 3.3.0 we still see:
```
Value is not within the valid range of the data type 'IEEE754LSBSingle': Infinity
```
Is this expected?

### 🕵️ Expected behavior

I expected that IEEE 754 infinities (positive and negative) as well as NaNs would be allowed.

### 📜 To Reproduce

1. Attempt to validate product with IEEE754LSBSingle Infinity
2. Observe validation failure

### 🖥 Environment Info

- Version of this software: 3.3.0
- Operating System: MacOs

### 📚 Version of Software Used

Version 3.3.0

### 🦄 Related requirements

🦄 #xyz

### I&T
TestRail Test ID: T8681192

**Comment by jordanpadams** [comment]
@msbentley I think the updates were just to support NANs, not INFs.

@al-niessner can you check me on that?

**Comment by al-niessner** [comment]
@jordanpadams @msbentley 

Let me start with from the content of the error message (type and value) it should not be an error.

We support NANs and INFs. Which of those we support are here:
https://github.com/NASA-PDS/validate/blob/8fef282524c6fb345f41738b9ea9e5e196a3cdc9/src/main/java/gov/nasa/pds/tools/validate/content/table/FieldValueValidator.java#L56-L57

We did have problems with the case and fixed it here:
https://github.com/NASA-PDS/validate/blob/8fef282524c6fb345f41738b9ea9e5e196a3cdc9/src/main/java/gov/nasa/pds/tools/validate/content/table/FieldValueValidator.java#L567

This is not say that the failure may be coming from somewhere else in the code or that whitespace is causing a problem or that there is spelling problem either side. It could also be that the type is not what we are looking for (remember this means whitespace, casing, etc):
https://github.com/NASA-PDS/validate/blob/8fef282524c6fb345f41738b9ea9e5e196a3cdc9/src/main/java/gov/nasa/pds/tools/validate/content/table/FieldValueValidator.java#L76-L80

If I can have the entire error message, then I can probably locate where this error originated and give a more detailed analysis of this rather than work we did.

**Comment by msbentley** [comment]
Thanks @al-niessner - sorry, I should have provided more details. This is an element in a binary array, not a table, one full error line looks like:
```
ERROR  [error.array.value_out_of_data_type_range]   array Data or index 1, location (240, 2, 2, 632): Value is not within the valid range of the data type 'IEEE754LSBSingle': Infinity
```

**Comment by al-niessner** [comment]
@jordanpadams @msbentley 

The error is here:
https://github.com/NASA-PDS/validate/blob/43fdf0d60db71c3e715bf2b182c716fabb6894a2/src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java#L303-L309

The range is not checking correctly for Infinity here:
https://github.com/NASA-PDS/validate/blob/43fdf0d60db71c3e715bf2b182c716fabb6894a2/src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java#L82-L83

The NAN and INF work done previously was on tables. This is definitely a deficiency on the part of validate. A small array and label as test data would be appreciated.

**Comment by jordanpadams** [comment]
@msbentley do you have a data product we could use to test with? (preferably small in size/truncated)

**Comment by msbentley** [comment]
Hi @jordanpadams, @al-niessner - hmm, I don't have an easy test case to hand that I can share here. I can try to send privately a not-yet-public data product.

**Comment by al-niessner** [comment]
@jordanpadams 

same as #761 same at this code 
https://github.com/NASA-PDS/validate/blob/56491e7b42cdae3984817fd874c3dcb79f199973/src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java#L302-L309

NaN and Inf are not special constants but rather dreary constants. Hence they are checked against range and it fails. The fix looks obvious but small sample should be procured to show that the fix works correctly.

**Comment by jordanpadams** [comment]
@al-niessner 

> NaN and Inf are not special constants but rather dreary constants

😆 copy that. @msbentley just sent over a file via email for additional testing.

**Comment by miguelp1986** [comment]
> @al-niessner
> 
> > NaN and Inf are not special constants but rather dreary constants
> 
> 😆 copy that. @msbentley just sent over a file via email for additional testing.

@jordanpadams can I get a copy of the test data if possible?

**Comment by al-niessner** [comment]
> > @al-niessner
> > > NaN and Inf are not special constants but rather dreary constants
> > 
> > 
> > 😆 copy that. @msbentley just sent over a file via email for additional testing.
> 
> @jordanpadams can I get a copy of the test data if possible?

https://github.com/NASA-PDS/validate/tree/main/src/test/resources/github785

**Comment by miguelp1986** [comment]
@al-niessner @jordanpadams  I don't see infinity values in that test data. Can I just change one of the following values to `"INF", "-INF", "+INF", "INFINITY",  "-INFINITY", "+INFINITY", "NAN", "-NAN", "+NAN"`?

```
2000-02-07T10:33:41.105     -0.293      0.756     -0.743
2000-02-07T10:33:41.136     -0.303      0.760     -0.746
2000-02-07T10:33:41.168     -0.308      0.762     -0.741
2000-02-07T10:33:41.195 -45729.855     77.777  20595.684
2000-02-07T10:33:41.199     -0.303      0.762     -0.741
2000-02-07T10:33:41.230     -0.294      0.765     -0.736
2000-02-07T10:33:41.258     77.777  57380.348  20601.990
2000-02-07T10:33:41.261     -0.294      0.769     -0.717
2000-02-07T10:33:41.292     -0.294      0.767     -0.721
2000-02-07T10:33:41.320 -9999999.9     77.777  20608.299
2000-02-07T10:33:41.324     -0.289      0.762     -0.719
2000-02-07T10:33:41.355     -0.289      0.765     -0.725
2000-02-07T10:33:41.383     77.777  -999999.9  20614.605
2000-02-07T10:33:41.386     -0.298      0.758     -0.739
2000-02-07T10:33:41.417     -0.288      0.752     -0.752
2000-02-07T10:33:41.445  6666666.6 -45729.844  20620.912
2000-02-07T10:33:41.449     -0.293      0.750     -0.756
2000-02-07T10:33:41.480     -0.298      0.759     -0.739
```

**Comment by miguelp1986** [comment]
I changed one of the values to `-INF` and it looks like the date type also needs to be changed from `ASCII_Real` to `IEEE754LSBSingle` judging by my error message? I'm not sure how to correctly test this.

```
      ERROR  [error.table.field_value_data_type_mismatch]   data object 1, record 4, field 2: Value does not match its data type 'ASCII_Real': -INF is not allowed
      ERROR  [error.table.field_value_not_a_number]   data object 1, record 4, field 2: Cannot cast field value '-INF' to a Number data type to validate against the min/max values defined in the label.
```

**Comment by miguelp1986** [comment]
@rchenatjpl provided the following test data with `inf` and `nan` values
[Archive (1).zip](https://github.com/NASA-PDS/validate/files/15225792/Archive.1.zip)
