### ISSUE TITLE
Validate-refs with manifest of file paths does not seem to read the files correctly

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#750]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I did:
```
validate-3.4.0-SNAPSHOT/bin/validate-refs --auth-opensearch config.properties manifest2.txt --verbose
```

I get:
```
14:54:13.949 [main] WARN  gov.nasa.pds.validate.ri.CommandLineInterface - Using Registry OpenSearch Database to check references.
14:54:13.957 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - lidvids will be sequentially processed.
14:54:13.957 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - Starting the reference integrity checks.
14:54:14.208 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - Summary:
14:54:14.208 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 products processed
14:54:14.209 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 missing references
14:54:14.209 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 fatals
14:54:14.209 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 errors not including missing references
14:54:14.210 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 warnings
```

### 🕵️ Expected behavior

I expected it would read in all the file paths and the XML files and check their references

### 📜 To Reproduce

```
validate-3.4.0-SNAPSHOT/bin/validate-refs --auth-opensearch config.properties manifest2.txt --verbose
```

### 🖥 Environment Info

Mac OSx
Java openJDK17

### 📚 Version of Software Used

Version 3.4.0-SNAPSHOT
Release Date: 2023-11-02 14:14:31

### 🩺 Test Data / Additional context

[manifest2.txt](https://github.com/NASA-PDS/validate/files/13244960/manifest2.txt) - points to data under `src/test/resources`

### I&T
TestRail Test ID: T8681194

**Comment by al-niessner** [comment]
@jordanpadams 

I will test it later today as I am doing heap problem first, but make sure there is an LF at the end of the line. If you leave off the LF the last line will be ignored. This is thanks to Oracle from this code:
https://github.com/NASA-PDS/validate/blob/43fdf0d60db71c3e715bf2b182c716fabb6894a2/src/main/java/gov/nasa/pds/validate/ri/UserInput.java#L30-L34

The Java supplied tools break the lines by LF or CRLF or CR but lines without them do not work. I tested with lidvid and it worked prior to release. Will try with label later just to make sure. The help used to say that all lines had to end with LF. Not sure if it still does.

**Comment by al-niessner** [comment]
@jordanpadams 

Not LF at end. Turns out that xmlModels is not working as expected. Diving in.
