### ISSUE TITLE
As a user, I want validate with the registry when a file is being referenced by more than one label

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#773]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Archivist

### 💪 Motivation

...so that I can use the registry to validate when more than one product references to the same file.

Related requirement:
- 🦄 #755

### Acceptance Criteria

**Given** a collection where >1 labels references the same file from `File_Area_*`
**When I perform** `validate-refs urn:pds:nasa:my_bundle::1.0`
**Then I expect** validate to throw an error

### I&T
TestRail Test ID: T8681201

**Comment by al-niessner** [comment]
@jordanpadams 

validate or validate-refs? Title or subject says validate while details says validate-refs

**Comment by al-niessner** [comment]
@jordanpadams 

This seems more like a sweeper. It would be simplest to scroll through all know opensearch docs, grab referenced files and if the set is not the same size as the list, then get lidvids of all duplicates. AKA, make opensearch do all the work.

validate-refs can do it as part of its normal processing, but it will put a big demand on memory. In #755 validate only looks once during each label. In theory, we could swap the map to/from disk to not hold all that memory but the peak usage would be the same. In validate-refs, accesses for this information is far more frequent so would have to remain in memory during the entire process or pay a big time penalty.

**Comment by jordanpadams** [comment]
@al-niessner I am thinking this would be a part of validate-refs. This will definitely be a part of the regular "sweeper" workflow to do validation of data across the archives, but I think we should also provide this capability in the event these products are being run through some type of pipeline (e.g. Nucleus), and we want to run this check on some subset of data.

Instead of paginating through, couldn't we just:
1. query for the LID(s)
2. extract the `ops:Data_File_Info/ops:file_ref`(s)
3. query the registry again to make sure no other LID had that `ops:Data_File_Info/ops:file_ref` value

**Comment by al-niessner** [comment]
@jordanpadams 

Can do it in a repetitive loop like you described but it will take a very long time (classic time vs memory). Basically, there is a lot more network traffic to make search. However many lids in DB that many searches. The time to search. The time to return the result. Does not sound like a lot on the surface but there millions of labels that can have multiple file areas so milliseconds (probably much bigger than that) turn into hours.

It may be possible to use aggregates of aggregates to have opensearch do the full task. Looking at that now.

**Comment by al-niessner** [comment]
@jordanpadams 

So, yes opensearch can do all of the work.

First, tell it to search all and have it build an aggregate. The aggregate is a set of buckets based on the value of ops:Data_File_Info/ops:file_ref. It would mean an aggregate of millions of buckets (read loads of memory). You can then ask for it to return all buckets with more than 1 item in it. Allowing this to be small relative to the full DB, could then go get all of their lids on the cheap.

Do file refs have to be absolute? If not, then if every label has a README reference that is relative to current directory, how does one avoid that false positive?

**Comment by jordanpadams** [comment]
> Do file refs have to be absolute?

If they are not, then they are invalid. That is another potential "sweeper" to check for invalid data would be if file_ref is not a valid URL.

**Comment by al-niessner** [comment]
@jordanpadams 

Used the m2020 pixl bundle from NASA-PDS/harvest#143 to build a test case since had it locally already. Created a new label from urn:nasa:pds:mars2020_pixl:data_oxides_pmc:ps__0125_0678032243_000rqa__00417120483005510000___j01 to rqd but changed nothing else. Hence, it should point all of the same data casuing a duplicate reference and the results show that this true.

Wrote the duplication check and its summary results look like this (there are loads of missing secondary references but we can ignore those):
```
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - Reference Summary:
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    22275 products processed
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    115290 missing references
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 fatals
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 errors not including missing references
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 warnings
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - Duplicate Summary:
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    Number of duplicates found: 2
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    File: ps__0125_0678032243_000rqa__00417120483005510000___j01.csv
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:mars2020_pixl:data_oxides_pmc:ps__0125_0678032243_000rqa__00417120483005510000___j01
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:mars2020_pixl:data_oxides_pmc:ps__0125_0678032243_000rqd__00417120483005510000___j01
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    File: readme.txt
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:mars2020.spice
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:insight_rad
15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:mars2020_pixl
```

Things to note. All files are relative with no path at all. This may be a side effect of how harvest was run but it may not. The labels validate on disk meaning it is not a poorly defined or structured labels. They are downloaded from the PDS site as given in the harvest ticket meaning that is how they are published to the world (why it is probably not an artifact of harvest). However, what is in the database is NOT the XML so harvest could have altered it during ingestion. Either way, it is a problem given there will be whole lot of READMEs.

**Comment by al-niessner** [comment]
@jordanpadams 

Change to file refs and report is now:
```
11:29:29.166 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - Duplicate Summary:
11:29:29.166 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    Number of duplicates found: 1
11:29:29.167 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    File: /home/niessner/Projects/PDS/harvest/src/test/resources/github143/data_oxides_pmc/sol_00125/ps__0125_0678032243_000rqa__00417120483005510000___j01.csv
11:29:29.168 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:mars2020_pixl:data_oxides_pmc:ps__0125_0678032243_000rqa__00417120483005510000___j01
11:29:29.168 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:mars2020_pixl:data_oxides_pmc:ps__0125_0678032243_000rqd__00417120483005510000___j01
```

**Comment by jordanpadams** [comment]
@al-niessner 🎉 Thanks! This is more expected.

**Comment by miguelp1986** [comment]
> @jordanpadams
> 
> Used the m2020 pixl bundle from [NASA-PDS/harvest#143](https://github.com/NASA-PDS/harvest/issues/143) to build a test case since had it locally already. Created a new label from urn:nasa:pds:mars2020_pixl:data_oxides_pmc:ps__0125_0678032243_000rqa__00417120483005510000___j01 to rqd but changed nothing else. Hence, it should point all of the same data casuing a duplicate reference and the results show that this true.
> 
> Wrote the duplication check and its summary results look like this (there are loads of missing secondary references but we can ignore those):
> 
> ```
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - Reference Summary:
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    22275 products processed
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    115290 missing references
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 fatals
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 errors not including missing references
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 warnings
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - Duplicate Summary:
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    Number of duplicates found: 2
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    File: ps__0125_0678032243_000rqa__00417120483005510000___j01.csv
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:mars2020_pixl:data_oxides_pmc:ps__0125_0678032243_000rqa__00417120483005510000___j01
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:mars2020_pixl:data_oxides_pmc:ps__0125_0678032243_000rqd__00417120483005510000___j01
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    File: readme.txt
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:mars2020.spice
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:insight_rad
> 15:45:14.943 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -       referer: urn:nasa:pds:mars2020_pixl
> ```
> 
> Things to note. All files are relative with no path at all. This may be a side effect of how harvest was run but it may not. The labels validate on disk meaning it is not a poorly defined or structured labels. They are downloaded from the PDS site as given in the harvest ticket meaning that is how they are published to the world (why it is probably not an artifact of harvest). However, what is in the database is NOT the XML so harvest could have altered it during ingestion. Either way, it is a problem given there will be whole lot of READMEs.

@al-niessner Can you share the command you used to test this? I downloaded a subset of the files in this bundle, created a new label like you did, and ran the following command:

```
validate-refs --auth-opensearch ~/Documents/PDS/validate_test_files/748/config.properties /Users/MPena/Documents/PDS/validate_test_files/773/urn-nasa-pds-mars2020_pixl/data_oxides_pmc/sol_00125/ps__0125_0678032243_000rqd__00417120483005510000___j01.xml --verbose
```

I'm not seeing any duplicates found, instead I see the following:

```
22:06:37.719 [main] WARN  gov.nasa.pds.validate.ri.CommandLineInterface - Using Registry OpenSearch Database to check references.
22:06:37.721 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - lidvids will be sequentially processed.
22:06:38.028 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - Starting the duplicate filename in FileArea checks.
22:06:38.029 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - Starting the reference integrity checks.
22:06:38.029 [main] INFO  gov.nasa.pds.validate.ri.Engine - Have 1 lidvids to check with 0 threads to get them done.
22:06:38.988 [main] ERROR Reference Integrity - The given lidvid 'urn:nasa:pds:mars2020_pixl:data_oxides_pmc:ps__0125_0678032243_000rqa__00417120483005510000___j01' is missing from the database.
22:06:39.488 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - Reference Summary:
22:06:39.488 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    1 products processed
22:06:39.489 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 missing references
22:06:39.489 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 fatals
22:06:39.489 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 errors not including missing references
22:06:39.489 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    0 warnings
22:06:39.489 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface - Duplicate Summary:
22:06:39.489 [main] INFO  gov.nasa.pds.validate.ri.CommandLineInterface -    Number of duplicates found: 0
```

**Comment by miguelp1986** [comment]
Jordan helped me realize what to do. I need to upload the bundle with the duplicate label to my local Registry instance using Harvest, and run the validate-refs command against the uploaded bundle.
