### ISSUE TITLE
Release v3.3.4?

### ISSUE THREAD

**Issue by cgobat** [NASA-PDS-Incubator/validate#775]
There exists a [tag for version 3.3.4](https://github.com/NASA-PDS/validate/releases/tag/v3.3.4), but there is/was no corresponding [GitHub release](https://github.com/NASA-PDS/validate/releases) (which currently jump straight from 3.3.3 to 3.4.0-SNAPSHOT). Was this intentional, or did the 3.3.4 release somehow get missed?

**Comment by jordanpadams** [comment]
@cgobat that was some very weird funkiness that happened in our automated CICD pipeline. Not sure what happened, but 3.3.3 is the latest tagged release. I just deleted 3.3.4 to remove the complication.
