### ISSUE TITLE
validate catches valid_maximum but not valid_minimum

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS-Incubator/validate#785]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

validate catches values above Special_Constants/valid_maximum but not values below Special_Constants/valid_minimum

### 🕵️ Expected behavior

The attached data file has 2 lines with values too large and 4 lines with values too small. Validate only calls out the large ones

### 📜 To Reproduce

% validate -t 00038_FGM_RTN.xml
PDS Validate Tool Report
Configuration:
   Version                       3.4.0-SNAPSHOT
   Date                          2023-12-08T22:34:00Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/00038_FGM_RTN.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/00038_FGM_RTN.xml
    Begin Content Validation: file:/Users/rchen/Desktop/00038_FGM_RTN.TAB
      WARNING  [warning.table.field_value_out_of_special_constant_min_max_range]   data object 1, record 7, field 3: Field has a value '57380.348' that is greater than the defined maximum value '44000.000'. 
      WARNING  [warning.table.field_value_out_of_special_constant_min_max_range]   data object 1, record 16, field 2: Field has a value '6666666.6' that is greater than the defined maximum value '44000.000'. 
    End Content Validation: file:/Users/rchen/Desktop/00038_FGM_RTN.TAB
        1 product validation(s) completed
Summary:
  0 error(s)
  2 warning(s)
  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    2            warning.table.field_value_out_of_special_constant_min_max_range
End of Report
Completed execution in 4400 ms

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 📚 Version of Software Used

% validate -V
gov.nasa.pds:validate
Version 3.4.0-SNAPSHOT
Release Date: 2023-12-06 19:26:36

### 🩺 Test Data / Additional context

[Archive.zip](https://github.com/NASA-PDS/validate/files/13621465/Archive.zip)

### 🦄 Related requirements

🦄 #xyz

### I&T Details
TestRail Test ID: T8681198

**Comment by miguelp1986** [comment]
TestRail Test ID: T8681198
