### ISSUE TITLE
Validate complains of missing CRLF line endings despite their presence

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS-Incubator/validate#820]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I ran `validate` on [this set of files](https://github.com/NASA-PDS/validate/files/14129618/CRLF.zip) using this command:
```
/tmp/validate-3.5.0-SNAPSHOT/bin/validate --target *.xml
```
I got told that the `magellan_gxdr_v1.0_20240201_transfer_manifest_v1.0.tab` file didn't have CRLF line endings. However, the Unix `file` command says it does:
```
$ file magellan_gxdr_v1.0_20240201_transfer_manifest_v1.0.tab
magellan_gxdr_v1.0_20240201_transfer_manifest_v1.0.tab: ASCII text, with very long lines (511), with CRLF line terminators
```
Also, opening the file in Hex Fiend shows `0D0A` with `0D` = `CR` and `0A` = `LF`.
<img width="841" alt="hex fiend" src="https://github.com/NASA-PDS/validate/assets/814813/cc8028af-9212-4093-b785-df61f79d4be3">

### 🕵️ Expected behavior

I expected better, frankly 😆

Just kidding. I guess I expected there to be no CRLF issues.

### 📜 To Reproduce

1. Build and install a recent Validate
2. Download the files in the ZIP archive (above)
3. Run `validate --target *.xml`

### 🖥 Environment Info

- Validate-3.5.0-SNAPSHOT
- macOS 14.2.1

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
For the example data cited, the `record_length` was incorrect, so validate was reading up to `CR`, and then everything gets out of whack. Closing as invalid.
