### ISSUE TITLE
Check for unlabeled files no longer works

### ISSUE THREAD

**Issue by tbarnes4** [NASA-PDS-Incubator/validate#822]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I run validate it no longer flags unlabled-files, even if the --allow-unlabled-files option is not called.

### 🕵️ Expected behavior

I expect that when I run validate that it will warn me when there are files that do not have labels, as prior versions did.

### 📜 To Reproduce

1. Grab a bundle or collection and ensure there is an unlabeled file in the directory.
2. Run validate.  Example:  validate -R pds4.bundle -t [point to bundle file OR bundle directory]
3.
...

### 🖥 Environment Info

- Version of this software tested: 3.3.3 and 3.4.1 (note it works in version 3.3.0 and prior)
- Operating Systems: MacOSX 12.6.8 and Red Hat Enterprise Linux 9.3
...

### 📚 Version of Software Used

gov.nasa.pds:validate
Version 3.4.1
Release Date: 2023-12-14 00:22:59

Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.

gov.nasa.pds:validate
Version 3.3.3
Release Date: 2023-11-20 23:43:57

Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@al-niessner we will loop back to this when we wrap up the Registry upgrades.

Note: I already created a [branch here](https://github.com/NASA-PDS/validate/tree/i822) for you to use, which includes a now broken test that should pass once we fix this bug.
