### ISSUE TITLE
Validate V.3.4.1 reports file read errors on products which read correctly under V.3.2.0

### ISSUE THREAD

**Issue by jmafi** [NASA-PDS-Incubator/validate#823]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I ran Validate on a PDS4 labeled (V.1.13.0.0) CDF-formatted file (which consists of a series of Array objects), Validate reports a read error. A previous version of Validate (3.2.0) read the file correctly.

### 🕵️ Expected behavior

I expected Validate to read the file correctly and report any other validation errors found.

### 📜 To Reproduce

1. Run Validate on the data product included in the attached zip file. The validate command used was: validate -t mvn_swi_l2_onboardsvymom_20230827_v02_r01.xml -r validate-3.4.1.txt
3.
4.
...

### 🖥 Environment Info

- Version of this software: Ubuntu 20.04
- Operating System: Linux
...

### 📚 Version of Software Used

3.4.1

### 🩺 Test Data / Additional context

[bug-bad_file_read.zip](https://github.com/NASA-PDS/validate/files/14172823/bug-bad_file_read.zip)

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details
The commit where this started: The commit where this started: https://github.com/NASA-PDS/validate/commit/4cd27c56e839e445c14a1857840c751a0fc9e634

The fatal errors now:
```
  FAIL: file:/Users/jpadams/Downloads/bug-bad_file_read/mvn_swi_l2_onboardsvymom_20230827_v02_r01.xml
    Begin Content Validation: file:/bug-bad_file_read/mvn_swi_l2_onboardsvymom_20230827_v02_r01.cdf
      FATAL_ERROR  [error.array.bad_file_read]   array time_met or index 1: Error occurred while reading data file: For input string: "9."
      FATAL_ERROR  [error.array.bad_file_read]   array time_unix or index 1: Error occurred while reading data file: For input string: "1.9"
      FATAL_ERROR  [error.array.bad_file_read]   array quality_flag or index 1: Error occurred while reading data file: For input string: "1.0"
      FATAL_ERROR  [error.array.bad_file_read]   array decom_flag or index 1: Error occurred while reading data file: For input string: "1.0"
      FATAL_ERROR  [error.array.bad_file_read]   array density or index 1: Error occurred while reading data file: For input string: "1000000.0"
      FATAL_ERROR  [error.array.bad_file_read]   array pressure or index 1: Error occurred while reading data file: For input string: "1000000.0"
      FATAL_ERROR  [error.array.bad_file_read]   array velocity or index 1: Error occurred while reading data file: For input string: "1.0E7"
      FATAL_ERROR  [error.array.bad_file_read]   array velocity_mso or index 1: Error occurred while reading data file: For input string: "1.0E7"
      FATAL_ERROR  [error.array.bad_file_read]   array temperature or index 1: Error occurred while reading data file: For input string: "1000000.0"
      FATAL_ERROR  [error.array.bad_file_read]   array temperature_mso or index 1: Error occurred while reading data file: For input string: "1000000.0"
    End Content Validation: file:/bug-bad_file_read/mvn_swi_l2_onboardsvymom_20230827_v02_r01.cdf
        1 product validation(s) completed
```

**Comment by msbentley** [comment]
Looks like it's related to changes in Special Constants handling for valid max/min. This is one area where the IM/standards are, IMO, a bit "soft" and it might be worth bringing this to DDWG at some point, if it's not already on the table?

**Comment by jordanpadams** [comment]
thanks @msbentley. That looks to be correct. Per [this commit](https://github.com/NASA-PDS/validate/commit/4cd27c56e839e445c14a1857840c751a0fc9e634), we added some more refined checks for min/max and looks like we are now having issues reading this data. will add it to the backlog for when our developer rolls off of some extensive work on the Registry.

**Comment by jordanpadams** [comment]
@jmafi in the interim, are you OK running v3.2.0 until we can get this fixed?

**Comment by jmafi** [comment]
@jordanpadams: can do
