### ISSUE TITLE
Validate stalls when validating collection inventory file with duplicates records

### ISSUE THREAD

**Issue by rsjoyner** [NASA-PDS-Incubator/validate#849]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

Validate crashes using this command:

validate_350 -t *.XML -r log.txt --schema PDS4_LADEE_1L00_1100.xsd --schematron PDS4_LADEE_1L00_1100.schwhen validating XML / CSV file using this command:

### 🕵️ Expected behavior

I expected Validate to not crash and complete the validation

### 📜 To Reproduce

1.   Unzip the 2 zip files in separate directories
2.   execute Validate using the above command
3.   1 zip should fail and 1 zip should complete
4.   Compare XMS and CSV files for differences

### 🖥 Environment Info

- Version of this software -- validate_3.5.0 
- Operating System -- Windows

### 📚 Version of Software Used

validate_3.5.0 

### 🩺 Test Data / Additional context

(1) data_raw.zip contains the amended files that Validate accurately validates
(2) validate_error.zip contains the original files that caused Validate to crash.
(3) As far as I can tell, the CSV file contained 2 duplicate records -- which when deleted, allowed validate to not crash

[data_raw.zip](https://github.com/NASA-PDS/validate/files/14485163/data_raw.zip)
[aaaValidate_Error.zip](https://github.com/NASA-PDS/validate/files/14485165/aaaValidate_Error.zip)

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@rsjoyner do you have the output from when it crashes?

**Comment by rsjoyner** [comment]
I don't have the output.   What I recall is that it wasn't a crash.  It was a "stall" where it never completed.

**Comment by jordanpadams** [comment]
@rsjoyner I was able to replicate the issue. We will have a look.

**Comment by al-niessner** [comment]
@jordanpadams 

Error, warning, or ignore duplicate entries?

**Comment by jordanpadams** [comment]
@al-niessner duplicate should throw an error
