### ISSUE TITLE
SXXP0003 Error when running on PDS3 data sets for v3.3.3 or v3.4.1

### ISSUE THREAD

**Issue by tbarnes4** [NASA-PDS-Incubator/validate#874]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I run validate v3.4.1 or v3.3.3 (but not v3.3.0 or before) on a PDS3 data set, my terminal gets flooded with errors that say something like:

> Error on line 1 column 1 of lsb_0408587281_0x53c_eng.lbl:
>  SXXP0003   Error reported by XML parser: Content is not allowed in prolog.: Content is not
>  allowed in prolog.

All error text matches exactly except for the filename.

This does not happen for every file in the PDS3 volume.  But I have seen it for labels describing ascii tables (like index.tab) or FITS files (but not all) or pointing to PNG files.  

When I run an older version of validate (v3.3.0 or v3.1.1), the terminal is not flooded with errors.  The report files match those from above (except for the version line and date stamp).  I'm not sure if this means the all these versions of validate are not reporting an issue in the report file and only now is validate flagging an error in the terminal, or if there is no error.

### 🕵️ Expected behavior

Not sure.  

### 📜 To Reproduce

1. Download [small](https://pdssbn.astro.umd.edu/holdings/nh-a-leisa-2-kem2-v1.0/dataset.shtml) or [larger](https://pdssbn.astro.umd.edu/holdings/nh-a-swap-3-kem2-v1.0/dataset.shtml) example PDS3 data set.
2. Run command:` validate -R pds3.volume`

### 🖥 Environment Info

- Versions of this software: 3.3.3 and 3.4.1 (but not v3.3.0 or v3.1.1)
- Operating System: macOS Monterey Version 12.7.4 and Red Hat Enterprise Linux version 9.3

### 📚 Version of Software Used

gov.nasa.pds:validate
Version 3.3.3
Release Date: 2023-11-20 23:43:57

gov.nasa.pds:validate
Version 3.4.1
Release Date: 2023-12-14 00:22:59

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@tbarnes4 I believe this is tightly coupled with https://github.com/NASA-PDS/validate/issues/854. We will see if the fixing of that bug fixes this one.

**Comment by tbarnes4** [comment]
@jordanpadams I was wondering that myself, but thought it might be different enough.  I guess we shall see.  Thanks!

**Comment by jordanpadams** [comment]
@tbarnes4 agreed. Your use cases is with PDS3 data so not sure if this will be fixed or not.

**Comment by al-niessner** [comment]
@jordanpadams Fixed with #854

**Comment by jordanpadams** [comment]
Skipping I&T since it is checked through other tests.
