### ISSUE TITLE
Validate failing products that contain "collection" not in the beginning of filename

### ISSUE THREAD

**Issue by klopez1313** [NASA-PDS-Incubator/validate#880]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

Validate is failing products that contain "collection" not in the beginning of filename. It is indeed an error to have "collection " as the start of a file name (unless it is the collection inventory) but its also failing files like ola_l2a_collection_overview.pdf which does not violate rule

### 🕵️ Expected behavior

I expected ola_l2a_collection_overview.pdf would pass validation

### 📜 To Reproduce

Here is the validate output: 
SKIP: file:/sbn/staging/orex/orex.ola_v5_0/document/ola_l2a_collection_overview.xml
      INFO  [info.integrity.unreferenced_file]   Skipping file:/sbn/staging/orex/orex.ola_v5_0/document/ola_l2a_collection_overview.xml due to collection not latest or does not sharing the same logical_identifier as the bundle target
...

### 🖥 Environment Info

- Version of this software validate-3.5.0-SNAPSHOT
- Operating System:  MacOSX 
...

### 📚 Version of Software Used

validate-3.5.0-SNAPSHOT

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@klopez1313 can you provide the command-line execution you used to run validate?

**Comment by klopez1313** [comment]
validate -R pds4.bundle -C /sbn/pds4-schema-files/catalog_orex.xml -r olav5.val.txt -t /sbn/staging/orex/orex.ola_v5_0

**Comment by jordanpadams** [comment]
@klopez1313 can you please provide the catalog file you are using and point us to the data collection online?

**Comment by klopez1313** [comment]
The data collection isnt online yet, is there another way I can send to you?

**Comment by jordanpadams** [comment]
@klopez1313 copy. we will try to create our own test data.

**Comment by jordanpadams** [comment]
@klopez1313 but can you provide us with the catalog file you were using?

**Comment by klopez1313** [comment]
<!DOCTYPE catalog
   PUBLIC "-//OASIS/DTD Entity Resolution XML Catalog V1.0//EN"
   "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    <group xml:base="pds4/mission/orex/v1/">
        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/mission/orex/v1/PDS4_OREX_1500" rewritePrefix="PDS4_OREX_1700_1500" />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/mission/orex/v1/PDS4_OREX_1500" rewritePrefix="PDS4_OREX_1700_1500" />
        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/orex/v1/PDS4_OREX_1500" rewritePrefix="PDS4_OREX_1700_1500" />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/orex/v1/PDS4_OREX_1500" rewritePrefix="PDS4_OREX_1700_1500" />

        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/mission/orex/v1/PDS4_OREX" rewritePrefix="orex_ldd_OREX" />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/mission/orex/v1/PDS4_OREX" rewritePrefix="orex_ldd_OREX" />
        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/orex/v1/PDS4_OREX" rewritePrefix="orex_ldd_OREX" />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/orex/v1/PDS4_OREX" rewritePrefix="orex_ldd_OREX" />

        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/orex/v1/" rewritePrefix="." />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/orex/v1/" rewritePrefix="." />
        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/mission/orex/v1/" rewritePrefix="." />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/mission/orex/v1/" rewritePrefix="." />
    </group>

    <group xml:base="pds4/">
        <uri name="https://pds.nasa.gov/pds4/sp/v1/PDS4_SP_1700_1100.sch.xsd" uri="sp/v1/PDS4_SP_1700_1100.xsd"/>
        <uri name="http://pds.nasa.gov/pds4/sp/v1/PDS4_SP_1700_1100.sch.xsd" uri="sp/v1/PDS4_SP_1700_1100.xsd"/>
    </group>

    <nextCatalog catalog="catalog_all.xml" />
</catalog>`

**Comment by klopez1313** [comment]
<!DOCTYPE catalog
   PUBLIC "-//OASIS/DTD Entity Resolution XML Catalog V1.0//EN"
   "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    <group xml:base="pds4/mission/orex/v1/">
        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/mission/orex/v1/PDS4_OREX_1500" rewritePrefix="PDS4_OREX_1700_1500" />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/mission/orex/v1/PDS4_OREX_1500" rewritePrefix="PDS4_OREX_1700_1500" />
        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/orex/v1/PDS4_OREX_1500" rewritePrefix="PDS4_OREX_1700_1500" />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/orex/v1/PDS4_OREX_1500" rewritePrefix="PDS4_OREX_1700_1500" />

        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/mission/orex/v1/PDS4_OREX" rewritePrefix="orex_ldd_OREX" />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/mission/orex/v1/PDS4_OREX" rewritePrefix="orex_ldd_OREX" />
        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/orex/v1/PDS4_OREX" rewritePrefix="orex_ldd_OREX" />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/orex/v1/PDS4_OREX" rewritePrefix="orex_ldd_OREX" />

        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/orex/v1/" rewritePrefix="." />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/orex/v1/" rewritePrefix="." />
        <rewriteURI uriStartString="https://pds.nasa.gov/pds4/mission/orex/v1/" rewritePrefix="." />
        <rewriteURI uriStartString="http://pds.nasa.gov/pds4/mission/orex/v1/" rewritePrefix="." />
    </group>

    <group xml:base="pds4/">
        <uri name="https://pds.nasa.gov/pds4/sp/v1/PDS4_SP_1700_1100.sch.xsd" uri="sp/v1/PDS4_SP_1700_1100.xsd"/>
        <uri name="http://pds.nasa.gov/pds4/sp/v1/PDS4_SP_1700_1100.sch.xsd" uri="sp/v1/PDS4_SP_1700_1100.xsd"/>
    </group>

    <nextCatalog catalog="catalog_all.xml" />
</catalog>

**Comment by klopez1313** [comment]
https://github.com/sbn-psi/pds4-schema-files/blob/master/catalog_orex.xml

**Comment by al-niessner** [comment]
@jordanpadams @klopez1313 

Sorry if I am missing something but what is the error here? In the description, I see no errors about the stated PDF file. I do see that there is an info and a skip. Both are related to same issue: The overview XML file which seems to be a collection is not the latest version (might be another XML file with same LID and higher version) or the LID in the collection does not start with the LID in the bundle. Given the command line and given the catalog which has no LID, I have no idea what should be happening. How is a catalog a bundle if it has no LID? Does validate need a -R pds4.catalog to do the right thing? Given the input is a catalog but told to process it as a bundle is this actually the correct response? How does any of this relate back to PDF or is that just a user typo?

Since I do not understand the problem statement, need a test data set with a command line and clear expectations to proceed. Some understanding of the catalog, its use, and what is trying to be done with this catalog and command line would probably be good too.

**Comment by jordanpadams** [comment]
@klopez1313 can you send me this collection label and inventory file, and the ola_l2a_collection_overview.xml and ola_l2a_collection_overview.pdf files via email? jordan.h.padams@jpl.nasa.gov

I created a test data set for what I think I am seeing here, and validation was successful:

```
$ validate-3.5.0-SNAPSHOT/bin/validate -R pds4.bundle -t src/test/resources/github880/bundle_mission.xml

PDS Validate Tool Report

Configuration:
   Version     3.5.0-SNAPSHOT
   Date        2024-05-02T17:38:49Z

Parameters:
   Targets                      [file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github880/bundle_mission.xml]
   Rule Type                    pds4.bundle
   Severity Level               WARNING
   Recurse Directories          true
   File Filters Used            [*.xml, *.XML]
   Data Content Validation      on
   Product Level Validation     on
   Allow Unlabeled Files        false
   Max Errors                   100000
   Registered Contexts File     /Users/jpadams/proj/pds/pdsen/workspace/validate/validate-3.5.0-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github880/bundle_mission.xml
        1 product validation(s) completed

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github880/document/orex_collection_description_doc.xml
        2 product validation(s) completed

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github880/document/collection_document.xml
        3 product validation(s) completed

PDS4 Bundle Level Validation Results

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github880/document/collection_document.xml
        1 integrity check(s) completed

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github880/bundle_mission.xml
        2 integrity check(s) completed

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github880/document/orex_collection_description_doc.xml
        3 integrity check(s) completed

Summary:

  3 product(s)
  0 error(s)
  0 warning(s)

  Product Validation Summary:
    3          product(s) passed
    0          product(s) failed
    0          product(s) skipped
    3          product(s) total

  Referential Integrity Check Summary:
    3          check(s) passed
    0          check(s) failed
    0          check(s) skipped
    3          check(s) total


End of Report
Completed execution in 6037 ms
```

Test data: 
[github880.tar.gz](https://github.com/NASA-PDS/validate/files/15192093/github880.tar.gz)

**Comment by jordanpadams** [comment]
Closing as invalid
