### ISSUE TITLE
`context_ref_mismatch` check only executes when -R pds4.label

### ISSUE THREAD

**Issue by tbarnes4** [NASA-PDS-Incubator/validate#915]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

I noticed that the #890 (doing context_ref_mismatch checks) only work when the default validate rule -R pds4.label is running.  The check is not made when using the rule pds4.folder, pds4.bundle, nor pds4.collection.  This makes this check practically useless when checking a delivery.  It only works if you specify each individual label file in the command line, not folders, label files.

### 🕵️ Expected behavior

I expected that the context_ref_mismatch check works for all 4 of the -R pds4.* rules.

### 📜 To Reproduce

Download small example collection: https://pdssbn.astro.umd.edu/holdings/pds4-nh_derived:pluto_albedo-v1.0/SUPPORT/dataset.shtml

Run the command:  validate -R pds4.collection -t collection.xml

### 🖥 Environment Info

- Operating System: MacOSX 12.7.4 and Red Hat Enterprise Linux 9.3

### 📚 Version of Software Used

gov.nasa.pds:validate
Version 3.5.1
Release Date: 2024-05-25 17:45:47

### 🩺 Test Data / Additional context

https://pdssbn.astro.umd.edu/holdings/pds4-nh_derived:pluto_albedo-v1.0/SUPPORT/dataset.shtml

### 🦄 Related requirements

#890

**Comment by al-niessner** [comment]
@jordanpadams 

These are the lines that matter:
https://github.com/NASA-PDS/validate/blob/ca6de71db6766340a2d9d275cec7f323ff83dea7/src/main/java/gov/nasa/pds/tools/validate/rule/pds4/ContextProductReferenceValidationRule.java#L106-L115

It references a fix to #42 and blame says that the check for !aLabel was there prior to the fix. The obvious solution is to remove the !aLabel check. For some reason validate thought it should only do this reference check for labels. Ringing any historical bells or just make the change and see what happens?

**Comment by jordanpadams** [comment]
@al-niessner not sure if I am understanding entirely correctly, but we want this check to apply for any rule used in execution. but we also want it only to apply to PDS4 XML labels. we don't want to perform this check on other files.

**Comment by jordanpadams** [comment]
@tbarnes4 the [latest SNAPSHOT](https://github.com/NASA-PDS/validate/releases/tag/v3.6.0-SNAPSHOT) should have this fix, let me know if you run into any issues

**Comment by tbarnes4** [comment]
@jordanpadams I did the quick check to see if the immediate problem is resolved, and it appears to be.  Now if there were any cascading affects of this, I'll have to see as time goes by (if I notice).  Thanks!
