### ISSUE TITLE
Configuration file parser does not reject incorrect options 

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS-Incubator/validate#923]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

I received a report from a data provider about unusual errors that they were encountering with validate. One of the issues that showed up in the report indicated that their schemas were not being loaded. The configuration file that they provided indicated that they used the option "validate_schema" instead of "validate.schema", so the schemas were not being loaded correctly.

### 🕵️ Expected behavior

I expected validate to fail when it encounters configuration options that it cannot handle.

### 📜 To Reproduce

create a configuration file that uses validate_schema instead of validate.schema and save it to config.txt
run `validate -c config.txt -t target`
Look for the " User Specified Schemas " section at the top of the report, which will be missing.

### 🖥 Environment Info

- Version of this software validate3.5.1
- Operating System: MacOSX with openjdk 21.0.3
...

### 📚 Version of Software Used

validate 3.5.1

### 🦄 Related requirements

🦄 #xyz

**Comment by al-niessner** [comment]
@jordanpadams 

Error or warning? I would think error but I can see a case for warning too.

**Comment by al-niessner** [comment]
@jordanpadams 

Code to detect unknown keywords. Need to know if you want it as error or warning. If error, bomb out like bad CLI arg or something else? I suggest failing immediately like when bad CLI arg is given.

**Comment by jordanpadams** [comment]
@al-niessner agreed. Lets fail like a CLI argument failure

**Comment by jordanpadams** [comment]
Skipping I&T since this is tested by other tickets in the test suite.
