### ISSUE TITLE
Validate does not show correct filename for PDF/A failures when validating a directory

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS-Incubator/validate#936]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I validated a document collection that had a non-pdfa pdf document, I noticed that the error for the PDF failure had the wrong filename. When I validate that document individually, the filename in the error is correct.

### 🕵️ Expected behavior

I expected the error report to have the correct filename for the failing file.

### 📜 To Reproduce

1. run validate on a document collection with a non-pdfa compliant pdf file, and probably other files that are pdfa compliant .
2. Check the pdf filename in the error report, and match it to the label filename
3. run validate only on the non-pdfa-compliant document
4. Observe that the pdf filename now matches the label

### 🖥 Environment Info

- Version of this software v3.5.1
- Operating System: Ubuntu 22.04.4 LTS with openjdk 11.0.23 2024-04-16

### 📚 Version of Software Used

gov.nasa.pds:validate
Version 3.5.1
Release Date: 2024-05-25 17:45:47

### 🩺 Test Data / Additional context

[single_file_match.txt](https://github.com/user-attachments/files/15828465/single_file_match.txt)
[multi-document-mismatch.txt](https://github.com/user-attachments/files/15828467/multi-document-mismatch.txt)

### 🦄 Related requirements

🦄 #xyz

**Comment by al-niessner** [comment]
@jstone-psi 

It would help immensely if you could tar or zip up file:/sbn/review-web/non-mission/LONEOS/gbo.ast.loneos.survey_V1_0/document and post it to this ticket.
